### ISSUE TITLE
Exception exporting Span, Attribute Error mappedproxy does not have attribute dropped

### ISSUE THREAD

**Issue by IronworksProductions** [pydantic/logfire#1017]
### Description

When attempting to instrument my application and send logs to it, I am running into this error:
Exception while exporting Span batch.
Traceback (most recent call last):
  File "/home/nix/.local/share/virtualenvs/Premium-Qe1WYDAp/lib/python3.10/site-packages/opentelemetry/sdk/trace/export/__init__.py", line 368, in _export_batch
    self.span_exporter.export(self.spans_list[:idx])  # type: ignore
  File "/home/nix/.local/share/virtualenvs/Premium-Qe1WYDAp/lib/python3.10/site-packages/logfire/_internal/exporters/remove_pending.py", line 45, in export
    return super().export(result)
  File "/home/nix/.local/share/virtualenvs/Premium-Qe1WYDAp/lib/python3.10/site-packages/logfire/_internal/exporters/wrapper.py", line 24, in export
    return self.wrapped_exporter.export(spans)
  File "/home/nix/.local/share/virtualenvs/Premium-Qe1WYDAp/lib/python3.10/site-packages/logfire/_internal/exporters/otlp.py", line 194, in export
    return super().export(spans)
  File "/home/nix/.local/share/virtualenvs/Premium-Qe1WYDAp/lib/python3.10/site-packages/logfire/_internal/exporters/wrapper.py", line 24, in export
    return self.wrapped_exporter.export(spans)
  File "/home/nix/.local/share/virtualenvs/Premium-Qe1WYDAp/lib/python3.10/site-packages/logfire/_internal/exporters/otlp.py", line 244, in export
    return super().export(spans)
  File "/home/nix/.local/share/virtualenvs/Premium-Qe1WYDAp/lib/python3.10/site-packages/logfire/_internal/exporters/wrapper.py", line 24, in export
    return self.wrapped_exporter.export(spans)
  File "/home/nix/.local/share/virtualenvs/Premium-Qe1WYDAp/lib/python3.10/site-packages/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py", line 136, in export
    serialized_data = encode_spans(spans).SerializeToString()
  File "/home/nix/.local/share/virtualenvs/Premium-Qe1WYDAp/lib/python3.10/site-packages/opentelemetry/exporter/otlp/proto/common/_internal/trace_encoder/__init__.py", line 58, in encode_spans
    resource_spans=_encode_resource_spans(sdk_spans)
  File "/home/nix/.local/share/virtualenvs/Premium-Qe1WYDAp/lib/python3.10/site-packages/opentelemetry/exporter/otlp/proto/common/_internal/trace_encoder/__init__.py", line 81, in _encode_resource_spans
    pb2_span = _encode_span(sdk_span)
  File "/home/nix/.local/share/virtualenvs/Premium-Qe1WYDAp/lib/python3.10/site-packages/opentelemetry/exporter/otlp/proto/common/_internal/trace_encoder/__init__.py", line 121, in _encode_span
    dropped_attributes_count=sdk_span.dropped_attributes,
  File "/home/nix/.local/share/virtualenvs/Premium-Qe1WYDAp/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py", line 390, in dropped_attributes
    return self._attributes.dropped
AttributeError: 'mappingproxy' object has no attribute 'dropped'

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="3.14.0"
platform="Linux-6.1.92-99.174.amzn2023.aarch64-aarch64-with-glibc2.34"
python="3.10.14 (main, Jun 14 2024, 00:11:04) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)]"
[related_packages]
requests="2.32.3"
pydantic="2.11.3"
openai="1.73.0"
protobuf="4.25.3"
rich="14.0.0"
tomli="2.2.1"
executing="2.2.0"
opentelemetry-api="1.21.0"
opentelemetry-exporter-otlp="1.21.0"
opentelemetry-exporter-otlp-proto-common="1.21.0"
opentelemetry-exporter-otlp-proto-grpc="1.21.0"
opentelemetry-exporter-otlp-proto-http="1.21.0"
opentelemetry-instrumentation="0.42b0"
opentelemetry-proto="1.21.0"
opentelemetry-sdk="1.21.0"
opentelemetry-semantic-conventions="0.42b0"
```
