### ISSUE TITLE
Logfire breaks with anthropic@0.50.0

### ISSUE THREAD

**Issue by boris-lapouga** [pydantic/logfire#1029]
### Description

Hi,

When attempting to use the `browser_use` tool, my dependency of anthropic@0.47.1 jumps to anthropic@0.50.0, which probably changed some API, and now the logfire instrumentation of Anthropic crashes with an error:

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/slack-agent/app/main.py", line 19, in <module>
    logfire.instrument_anthropic()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Caches/pypoetry/virtualenvs/slack-agent-V_9GKwnk-py3.12/lib/python3.12/site-packages/logfire/_internal/main.py", line 1230, in instrument_anthropic
    return instrument_llm_provider(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Caches/pypoetry/virtualenvs/slack-agent-V_9GKwnk-py3.12/lib/python3.12/site-packages/logfire/_internal/integrations/llm_providers/llm_provider.py", line 43, in instrument_llm_provider
    instrument_llm_provider(
  File "/Library/Caches/pypoetry/virtualenvs/slack-agent-V_9GKwnk-py3.12/lib/python3.12/site-packages/logfire/_internal/integrations/llm_providers/llm_provider.py", line 71, in instrument_llm_provider
    client._original_request_method = original_request_method = client._request
                                                                ^^^^^^^^^^^^^^^
AttributeError: type object 'Anthropic' has no attribute '_request'. Did you mean: 'request'?`

The new package update seems to have changed to self.request

I can confirm it works if I update your source code in llm_provider.py to:
`client._is_instrumented_by_logfire = True
    if hasattr(client, "_request"):
        client._original_request_method = original_request_method = client._request
    elif hasattr(client, "request"):
        client._original_request_method = original_request_method = client.request
    else:
        raise AttributeError("Client must have either '_request' or 'request' method")`

Could be really nice to have it patched officially, so people can use latest package version of Anthropic and other tools. 

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="3.14.0"
platform="macOS-15.3.2-arm64-arm-64bit"
python="3.12.3 (main, May 25 2024, 20:55:05) [Clang 15.0.0 (clang-1500.3.9.4)]"
[related_packages]
requests="2.32.3"
pydantic="2.10.6"
openai="1.75.0"
protobuf="5.29.3"
rich="13.9.4"
executing="2.2.0"
opentelemetry-api="1.30.0"
opentelemetry-exporter-otlp-proto-common="1.30.0"
opentelemetry-exporter-otlp-proto-http="1.30.0"
opentelemetry-instrumentation="0.51b0"
opentelemetry-instrumentation-aiohttp-client="0.51b0"
opentelemetry-instrumentation-httpx="0.51b0"
opentelemetry-instrumentation-sqlalchemy="0.51b0"
opentelemetry-proto="1.30.0"
opentelemetry-sdk="1.30.0"
opentelemetry-semantic-conventions="0.51b0"
opentelemetry-util-http="0.51b0"
```
