### ISSUE TITLE
Pydantic logfire crashed my server

### ISSUE THREAD

**Issue by AlbertMitjans** [pydantic/logfire#1056]
### Description

Last Friday May 2nd (out of nowhere, the last deployment was on Thursday), the Swap Usage of my server started increasing, until it reached 100% and the server stopped working:

![Image](https://github.com/user-attachments/assets/0b08af9d-fba4-4a03-8587-112e315cf859)

I was getting the following errors in the logs:
```
17:29:13.230 Metric collection timed out. Will try again after 60.0 seconds
             │ opentelemetry.sdk.metrics._internal.exceptions.MetricsTimeoutError: Timed out while executing callback
             │ Traceback (most recent call last):
             │   File "/home/ppadmin/sellebrate/.venv/lib/python3.10/site-packages/opentelemetry/sdk/metrics/_internal/export/__init__.py", line 524, in _ticker
             │     self.collect(timeout_millis=self._export_timeout_millis)
             │   File "/home/ppadmin/sellebrate/.venv/lib/python3.10/site-packages/opentelemetry/sdk/metrics/_internal/export/__init__.py", line 340, in collect
             │     metrics = self._collect(self, timeout_millis=timeout_millis)
             │   File "/home/ppadmin/sellebrate/.venv/lib/python3.10/site-packages/opentelemetry/sdk/metrics/_internal/measurement_consumer.py", line 126, in collect
             │     raise MetricsTimeoutError(
             │ opentelemetry.sdk.metrics._internal.exceptions.MetricsTimeoutError: Timed out while executing callback
Currently retrying 1 failed export(s)
Currently retrying 1 failed export(s)
```

After commenting out the following lines the issue was fixed:
![Image](https://github.com/user-attachments/assets/b12fb05b-d7ec-4a0f-912a-5f878d3efd5c)

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="3.14.0"
platform="Linux-5.15.0-107-generic-x86_64-with-glibc2.35"
python="3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]"
[related_packages]
requests="2.32.3"
pydantic="2.5.0"
fastapi="0.115.8"
openai="1.63.2"
protobuf="5.29.3"
rich="13.9.4"
tomli="2.2.1"
executing="2.2.0"
opentelemetry-api="1.32.0"
opentelemetry-exporter-otlp-proto-common="1.32.0"
opentelemetry-exporter-otlp-proto-http="1.32.0"
opentelemetry-instrumentation="0.53b0"
opentelemetry-instrumentation-asgi="0.53b0"
opentelemetry-instrumentation-fastapi="0.53b0"
opentelemetry-instrumentation-redis="0.53b0"
opentelemetry-instrumentation-requests="0.53b0"
opentelemetry-instrumentation-sqlalchemy="0.53b0"
opentelemetry-instrumentation-system-metrics="0.53b0"
opentelemetry-proto="1.32.0"
opentelemetry-sdk="1.32.0"
opentelemetry-semantic-conventions="0.53b0"
opentelemetry-util-http="0.53b0"
```
