### ISSUE TITLE
Verification link for billing email not being sent

### ISSUE THREAD

**Issue by owentran** [pydantic/logfire#1081]
### Description

Hi. I'm adding a payment method and trying to use a different email for receipts. I checked my spam folder but no joy. Does the billing email have to be a member of the project? Can you update the billing email for me? Thanks.

https://logfire-us.pydantic.dev/marit/-/settings/payment/payment-information

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="3.14.1"
platform="macOS-15.4.1-arm64-arm-64bit"
python="3.12.6 (main, Sep  9 2024, 21:36:32) [Clang 18.1.8 ]"
[related_packages]
requests="2.32.3"
pydantic="2.11.1"
fastapi="0.115.12"
protobuf="5.29.4"
rich="14.0.0"
executing="2.2.0"
opentelemetry-api="1.32.1"
opentelemetry-exporter-otlp-proto-common="1.32.1"
opentelemetry-exporter-otlp-proto-http="1.32.1"
opentelemetry-instrumentation="0.53b1"
opentelemetry-instrumentation-aiohttp-client="0.53b1"
opentelemetry-instrumentation-redis="0.53b1"
opentelemetry-instrumentation-sqlalchemy="0.53b1"
opentelemetry-instrumentation-system-metrics="0.53b1"
opentelemetry-proto="1.32.1"
opentelemetry-sdk="1.32.1"
opentelemetry-semantic-conventions="0.53b1"
opentelemetry-util-http="0.53b1"
```
