### ISSUE TITLE
`logfire inspect` is missing `psycopg` in the report

### ISSUE THREAD

**Issue by Elkiwa** [pydantic/logfire#114]
### Description

1. Install psycopg in a fastapi project
2. Install logfire and use `logfire inspect` to get a report like the following:
```
The following packages from your environment have an OpenTelemetry instrumentation that is not installed:
┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Package    ┃ OpenTelemetry instrumentation package    ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ fastapi    │ opentelemetry-instrumentation-fastapi    │
│ httpx      │ opentelemetry-instrumentation-httpx      │
│ jinja2     │ opentelemetry-instrumentation-jinja2     │
│ requests   │ opentelemetry-instrumentation-requests   │
│ sqlalchemy │ opentelemetry-instrumentation-sqlalchemy │
│ sqlite3    │ opentelemetry-instrumentation-sqlite3    │
│ urllib     │ opentelemetry-instrumentation-urllib     │
│ urllib3    │ opentelemetry-instrumentation-urllib3    │
└────────────┴──────────────────────────────────────────┘
```
3. Expectation:
```
The following packages from your environment have an OpenTelemetry instrumentation that is not installed:
┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Package    ┃ OpenTelemetry instrumentation package    ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ fastapi    │ opentelemetry-instrumentation-fastapi    │
│ httpx      │ opentelemetry-instrumentation-httpx      │
│ jinja2     │ opentelemetry-instrumentation-jinja2     │
│ psycopg    │ opentelemetry-instrumentation-psycopg    │
│ requests   │ opentelemetry-instrumentation-requests   │
│ sqlalchemy │ opentelemetry-instrumentation-sqlalchemy │
│ sqlite3    │ opentelemetry-instrumentation-sqlite3    │
│ urllib     │ opentelemetry-instrumentation-urllib     │
│ urllib3    │ opentelemetry-instrumentation-urllib3    │
└────────────┴──────────────────────────────────────────┘
```

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="0.29.0"
platform="Windows-11-10.0.22631-SP0"
python="3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]"
[related_packages]
requests="2.31.0"
pydantic="2.7.1"
fastapi="0.110.3"
openai="0.28.1"
protobuf="4.25.3"
rich="13.7.1"
opentelemetry-api="1.24.0"
opentelemetry-exporter-otlp-proto-common="1.24.0"
opentelemetry-exporter-otlp-proto-http="1.24.0"
opentelemetry-instrumentation="0.45b0"
opentelemetry-proto="1.24.0"
opentelemetry-sdk="1.24.0"
opentelemetry-semantic-conventions="0.45b0"
```
