### ISSUE TITLE
Unable to see traces for openai Agents in celery task - works fine if run directly in my fastapi app

### ISSUE THREAD

**Issue by adiberk** [pydantic/logfire#1143]
### Description

I am trying to instrument the openai agents
`logfire.instrument_openai_agents()`

And whether I do this in the celery main file or inside the `@worker_init.connect` - I am unable to get traces to show up.

To add - I would rather not auto instrument celery itself which I know is something your docs say you can do in the worker_init.connect, as I just don't need those traces (just agent stuff)

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="3.19.0"
platform="Linux-6.10.14-linuxkit-aarch64-with-glibc2.36"
python="3.11.13 (main, Jun 11 2025, 06:35:21) [GCC 12.2.0]"
[related_packages]
requests="2.32.3"
pydantic="2.10.6"
fastapi="0.115.12"
openai="1.86.0"
protobuf="5.29.5"
rich="13.9.4"
executing="2.2.0"
opentelemetry-api="1.31.1"
opentelemetry-exporter-otlp-proto-common="1.31.1"
opentelemetry-exporter-otlp-proto-http="1.31.1"
opentelemetry-instrumentation="0.52b1"
opentelemetry-instrumentation-celery="0.52b1"
opentelemetry-proto="1.31.1"
opentelemetry-sdk="1.31.1"
opentelemetry-semantic-conventions="0.52b1"
```
