### ISSUE TITLE
Alerts not being sent

### ISSUE THREAD

**Issue by mattaliev** [pydantic/logfire#1157]
### Description

I have created 2 alert channels: 1 for slack (new format) and 1 for discord (legacy slack format). I was able to send test webhooks to both channels, but when it comes to alerts, it doesn't work. 

I have set my alert to send "when query has results" and I can see in web UI that the runs have matches, but the message never comes to slack or discord.

P.s. I am aware that alerts are still in beta, just posting it here so that team is aware of the issue

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="3.8.0"
platform="macOS-15.4.1-x86_64-i386-64bit"
python="3.12.6 (v3.12.6:a4a2d2b0d85, Sep  6 2024, 16:08:03) [Clang 13.0.0 (clang-1300.0.29.30)]"
[related_packages]
requests="2.32.3"
pydantic="2.10.6"
fastapi="0.115.8"
openai="1.75.0"
protobuf="5.29.3"
rich="13.9.4"
tomli="2.2.1"
executing="2.2.0"
opentelemetry-api="1.30.0"
opentelemetry-exporter-otlp-proto-common="1.30.0"
opentelemetry-exporter-otlp-proto-grpc="1.30.0"
opentelemetry-exporter-otlp-proto-http="1.30.0"
opentelemetry-instrumentation="0.51b0"
opentelemetry-instrumentation-asgi="0.51b0"
opentelemetry-instrumentation-celery="0.51b0"
opentelemetry-instrumentation-fastapi="0.51b0"
opentelemetry-proto="1.30.0"
opentelemetry-sdk="1.30.0"
opentelemetry-semantic-conventions="0.51b0"
opentelemetry-semantic-conventions-ai="0.4.3"
opentelemetry-util-http="0.51b0"
```
