### ISSUE TITLE
Logfire auto-tracing breaks importlib files

### ISSUE THREAD

**Issue by slobodaapl** [pydantic/logfire#1211]
### Description

When we auto-trace our package:
```python
logfire.install_auto_tracing(modules=["my_pkg"], min_duration=0.10)

from my_pkg.app import app
```

We get:

```python
  File "/app/.venv/lib/python3.12/site-packages/my_pkg/util/message_handler.py", line 223, in load_prompt
    with (files("my_pkg.resources") / filename).open(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/resources/_adapters.py", line 139, in open
    raise FileNotFoundError("Can't open orphan path")
FileNotFoundError: Can't open orphan path
```

Otherwise, it works fine if not auto-traced. The package is installed with uv with options:
`uv sync --locked --no-editable`

Pyproject.toml includes the resources properly:
```toml
[tool.setuptools.package-data]
"my_pkg" = ["**/*.data"]
```

### Python, Logfire & OS Versions, related packages (not required)

```TOML
Logfire info output:

logfire="3.16.1"
platform="Linux-5.14.0-284.30.1.el9_2.x86_64-x86_64-with-glibc2.36"
python="3.12.11 (main, Jun 10 2025, 23:56:19) [GCC 12.2.0]"
[related_packages]
requests="2.32.3"
pydantic="2.11.4"
fastapi="0.115.12"
openai="1.77.0"
protobuf="5.29.4"
rich="14.0.0"
executing="2.2.0"
opentelemetry-api="1.32.1"
opentelemetry-exporter-otlp-proto-common="1.32.1"
opentelemetry-exporter-otlp-proto-http="1.32.1"
opentelemetry-instrumentation="0.53b1"
opentelemetry-instrumentation-asgi="0.53b1"
opentelemetry-instrumentation-fastapi="0.53b1"
opentelemetry-instrumentation-sqlalchemy="0.53b1"
opentelemetry-proto="1.32.1"
opentelemetry-sdk="1.32.1"
opentelemetry-semantic-conventions="0.53b1"
opentelemetry-util-http="0.53b1"
```
