### ISSUE TITLE
Process is still ongoing on Live View dashboard despite exception raised

### ISSUE THREAD

**Issue by lironesamoun** [pydantic/logfire#187]
### Description

I have created a toy code for playing with logfire:

```
import logfire
import logging
import time

def timed_execution(func):
    """Decorator to measure execution time of a function."""
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        execution_time = end_time - start_time
        logfire.info(f"Execution time of {func.__name__}: {execution_time:.4f} seconds")
        return result
    return wrapper

@timed_execution
@logfire.instrument("Step 1", extract_args=True)
def step_1(condition):
    logfire.debug("Executing Step 1")
    print("STEP 1")
    time.sleep(2)  # Simulating processing time
    if condition == 'A':
        sub_step_1_A()
    else:
        sub_step_1_B()
    # Simulating an error
    result = 1 / 0

@timed_execution
@logfire.instrument("Sub Step 1.A", extract_args=True)
def sub_step_1_A():
    logfire.debug("Executing Sub Step 1.A")
    print("Sub Step 1.A")
    time.sleep(1)  # Simulating processing time

@timed_execution
@logfire.instrument("Sub Step 1.B", extract_args=True)
def sub_step_1_B():
    logfire.debug("Executing Sub Step 1.B")
    print("Sub Step 1.B")
    time.sleep(1)  # Simulating processing time

@timed_execution
@logfire.instrument("Step 2", extract_args=True)
def step_2(condition):
    logfire.debug("Executing Step 2")
    print("STEP 2")
    time.sleep(2)  # Simulating processing time
    nested_function()
    if condition == 'A':
        sub_step_2_A()
    else:
        sub_step_2_B()

@timed_execution
@logfire.instrument("Sub Step 2.A", extract_args=True)
def sub_step_2_A():
    logfire.debug("Executing Sub Step 2.A")
    print("Sub Step 2.A")
    time.sleep(1)  # Simulating processing time

@timed_execution
@logfire.instrument("Sub Step 2.B", extract_args=True)
def sub_step_2_B():
    logfire.debug("Executing Sub Step 2.B")
    print("Sub Step 2.B")
    time.sleep(1)  # Simulating processing time

@timed_execution
@logfire.instrument("Nested Function", extract_args=True)
def nested_function():
    logfire.debug("Executing Nested Function")
    print("Nested function")
    time.sleep(1)  # Simulating processing time
    # Simulating a debug message
    logfire.debug("Nested function executed successfully")

@timed_execution
@logfire.instrument("Step 3", extract_args=True)
def step_3(condition):
    logfire.debug("Executing Step 3")
    print("STEP 3")
    time.sleep(2)  # Simulating processing time
    if condition == 'A':
        sub_step_3_A()
    else:
        sub_step_3_B()
    # Simulating a warning
    logfire.warn("This is a warning in Step 3")

@timed_execution
@logfire.instrument("Sub Step 3.A", extract_args=True)
def sub_step_3_A():
    logfire.debug("Executing Sub Step 3.A")
    print("Sub Step 3.A")
    time.sleep(1)  # Simulating processing time

@timed_execution
@logfire.instrument("Sub Step 3.B", extract_args=True)
def sub_step_3_B():
    logfire.debug("Executing Sub Step 3.B")
    print("Sub Step 3.B")
    time.sleep(1)  # Simulating processing time

@timed_execution
@logfire.instrument("Pipeline", extract_args=True)
def run_pipeline(condition):
    logfire.info("Starting the pipeline")
    try:
        step_1(condition)
        step_2(condition)
        step_3(condition)
    except Exception as e:
        logfire.error(f"An error occurred: {e}")
    finally:
        logfire.info("Pipeline execution completed")

if __name__ == '__main__':
    condition = 'A'
    run_pipeline(condition)

```

This is the output:

```
13:47:53.277 Pipeline
13:47:53.279   Starting the pipeline
13:47:53.280   Step 1
STEP 1
13:47:55.285     Sub Step 1.A
Sub Step 1.A
13:47:56.298     Execution time of sub_step_1_A: 1.0066 seconds
13:47:57.085   An error occurred: division by zero
13:47:57.085   Pipeline execution completed
13:47:57.086 Execution time of run_pipeline: 4.2593 seconds
```

So far so good. However on the live view section on the dashboard, I get this:
<img width="1271" alt="image" src="https://github.com/pydantic/logfire/assets/8614763/df0b7332-dfe3-4117-9540-b370867302fa">

The process is still ongoing without any trace of the exception. 

Did I miss something ? 
I take advantage as well of this post to ask you is there a way to put directly a tag on the decorator ?

thank in advance

### Python, Logfire & OS Versions, related packages (not required)

```TOML
·> logfire info
logfire="0.32.1"
platform="macOS-14.4.1-arm64-arm-64bit"
python="3.11.2 (main, Feb 24 2023, 14:47:46) [Clang 14.0.0 (clang-1400.0.29.202)]"
[related_packages]
requests="2.31.0"
pydantic="1.10.13"
fastapi="0.109.2"
openai="1.17.0"
protobuf="4.25.3"
rich="13.7.0"
executing="2.0.1"
opentelemetry-api="1.24.0"
opentelemetry-exporter-otlp-proto-common="1.24.0"
opentelemetry-exporter-otlp-proto-http="1.24.0"
opentelemetry-instrumentation="0.45b0"
opentelemetry-instrumentation-asgi="0.45b0"
opentelemetry-instrumentation-asyncpg="0.45b0"
opentelemetry-instrumentation-dbapi="0.45b0"
opentelemetry-instrumentation-fastapi="0.45b0"
opentelemetry-instrumentation-grpc="0.45b0"
opentelemetry-instrumentation-httpx="0.45b0"
opentelemetry-instrumentation-jinja2="0.45b0"
opentelemetry-instrumentation-mysql="0.45b0"
opentelemetry-instrumentation-pymysql="0.45b0"
opentelemetry-instrumentation-requests="0.45b0"
opentelemetry-instrumentation-sqlalchemy="0.45b0"
opentelemetry-instrumentation-sqlite3="0.45b0"
opentelemetry-instrumentation-tornado="0.45b0"
opentelemetry-instrumentation-urllib="0.45b0"
opentelemetry-instrumentation-urllib3="0.45b0"
opentelemetry-proto="1.24.0"
opentelemetry-sdk="1.24.0"
opentelemetry-semantic-conventions="0.45b0"
opentelemetry-util-http="0.45b0"
```
