### ISSUE TITLE
 psutil 5.9.8 not supported

### ISSUE THREAD

**Issue by SaboniAmine** [pydantic/logfire#192]
### Description

Hello,

While working on code carbon integration, I encountered an incompatibility of logfire & latest psutil version. We use it only for test purposes, so I'm not asking a change from your side, but just to inform you that there is a total incompatibility, both auth/info return the same error:

> logfire auth
Traceback (most recent call last):
  File "/Users/amine/anaconda3/envs/cc/bin/logfire", line 5, in <module>
    from logfire.cli import main
  File "/Users/amine/anaconda3/envs/cc/lib/python3.9/site-packages/logfire/__init__.py", line 7, in <module>
    from ._internal.auto_trace import AutoTraceModule
  File "/Users/amine/anaconda3/envs/cc/lib/python3.9/site-packages/logfire/_internal/auto_trace/__init__.py", line 9, in <module>
    from .import_hook import LogfireFinder
  File "/Users/amine/anaconda3/envs/cc/lib/python3.9/site-packages/logfire/_internal/auto_trace/import_hook.py", line 11, in <module>
    from .rewrite_ast import exec_source
  File "/Users/amine/anaconda3/envs/cc/lib/python3.9/site-packages/logfire/_internal/auto_trace/rewrite_ast.py", line 11, in <module>
    from ..ast_utils import BaseTransformer, LogfireArgs
  File "/Users/amine/anaconda3/envs/cc/lib/python3.9/site-packages/logfire/_internal/ast_utils.py", line 14, in <module>
    from .stack_info import StackInfo, get_filepath_attribute
  File "/Users/amine/anaconda3/envs/cc/lib/python3.9/site-packages/logfire/_internal/stack_info.py", line 10, in <module>
    import opentelemetry.sdk.trace
  File "/Users/amine/anaconda3/envs/cc/lib/python3.9/site-packages/opentelemetry/sdk/trace/__init__.py", line 59, in <module>
    from opentelemetry.sdk.resources import Resource
  File "/Users/amine/anaconda3/envs/cc/lib/python3.9/site-packages/opentelemetry/sdk/resources/__init__.py", line 79, in <module>
    import psutil
  File "/Users/amine/anaconda3/envs/cc/lib/python3.9/site-packages/psutil/__init__.py", line 123, in <module>
    from . import _psosx as _psplatform
  File "/Users/amine/anaconda3/envs/cc/lib/python3.9/site-packages/psutil/_psosx.py", line 37, in <module>
    PAGESIZE = cext_posix.getpagesize()
AttributeError: module 'psutil._psutil_posix' has no attribute 'getpagesize'

running with psutil 5.7.3 is totally fine, we'll do the switch from our side.

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="0.33.0"
platform="macOS-14.5-arm64-arm-64bit"
python="3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:55:20) 
[Clang 16.0.6 ]"
[related_packages]
requests="2.28.1"
pydantic="2.7.1"
fastapi="0.111.0"
protobuf="4.25.3"
rich="13.7.1"
tomli="2.0.1"
executing="2.0.1"
opentelemetry-api="1.24.0"
opentelemetry-exporter-otlp-proto-common="1.24.0"
opentelemetry-exporter-otlp-proto-http="1.24.0"
opentelemetry-instrumentation="0.45b0"
opentelemetry-proto="1.24.0"
opentelemetry-sdk="1.24.0"
opentelemetry-semantic-conventions="0.45b0"
```
