### ISSUE TITLE
auth keeps defaulting to non-existent project

### ISSUE THREAD

**Issue by inimaz** [pydantic/logfire#209]
### Description

Hello team!

I had a project called `codecarbon` that I have **deleted**.

And a file that contains just metric_gauges so it is using the default logfire instance.
Content of the file:
```
from logfire import metric_gauge
duration_gauge = metric_gauge(
    "codecarbon_duration", unit="(s)", description="Duration from last measure"
)

duration.set(data.duration)
...
```

The problem is, when I run this file, it keeps connecting to the old project that I have already deleted
```

inimaz:~/$  python logfire_metrics.py

Logfire project URL: https://logfire.pydantic.dev/inimaz/codecarbon              <==================
...
```
And I cannot see the metrics in any existing project.

I have tried removing the token in `.logfire/default.toml` and rerunning `logfire auth`, but I still see that it points to the deleted project. Is this normal?

Thanks a lot!

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="0.32.0"
platform="Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.31"
python="3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0]"
[related_packages]
requests="2.31.0"
protobuf="4.25.3"
rich="13.7.1"
opentelemetry-api="1.24.0"
opentelemetry-exporter-otlp-proto-common="1.24.0"
opentelemetry-exporter-otlp-proto-http="1.24.0"
opentelemetry-instrumentation="0.45b0"
opentelemetry-proto="1.24.0"
opentelemetry-sdk="1.24.0"
opentelemetry-semantic-conventions="0.45b0"
```
