### ISSUE TITLE
No module named 'openai._legacy_response'

### ISSUE THREAD

**Issue by maximepeabody** [pydantic/logfire#234]
### Description

I'm trying to integrate with openai. I have openai==1.3.5

I'm seeing this error:

No module named 'openai._legacy_response'

My code is like:

openai_client = openai.Client()
logfire.configure()
logfire.instrument_openai(openai_client)

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="0.39.0"
platform="macOS-14.4-arm64-arm-64bit"
python="3.10.14 (main, May 24 2024, 14:58:47) [Clang 15.0.0 (clang-1500.3.9.4)]"
[related_packages]
requests="2.31.0"
pydantic="2.7.0"
fastapi="0.109.2"
openai="1.3.5"
protobuf="4.25.3"
rich="13.7.1"
tomli="2.0.1"
executing="2.0.1"
opentelemetry-api="1.25.0"
opentelemetry-exporter-otlp-proto-common="1.25.0"
opentelemetry-exporter-otlp-proto-http="1.25.0"
opentelemetry-instrumentation="0.46b0"
opentelemetry-instrumentation-asgi="0.46b0"
opentelemetry-instrumentation-fastapi="0.46b0"
opentelemetry-proto="1.25.0"
opentelemetry-sdk="1.25.0"
opentelemetry-semantic-conventions="0.46b0"
opentelemetry-util-http="0.46b0"
```
