### ISSUE TITLE
Failed to introspect calling code

### ISSUE THREAD

**Issue by imnotdev25** [pydantic/logfire#276]
### Description

Failed to introspect calling code. Please report this issue to Logfire. Falling back to normal message formatting which may result in loss of information if using an f-string. Set inspect_arguments=False in logfire.configure() to suppress this warning. The problem was:
`executing` failed to find a node.

I tried to set parameter but still same. 

Traceback: 

Traceback (most recent call last):
  File "/root/PycharmProjects/backend-user-form-api/.venv/lib/python3.11/site-packages/logfire/_internal/utils.py", line 236, in handle_internal_errors
    yield
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/PycharmProjects/backend-user-form-api/.venv/lib/python3.11/site-packages/logfire/_internal/main.py", line 1613, in set_attribute
    self._json_schema_properties[key] = create_json_schema(value, set())
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/PycharmProjects/backend-user-form-api/.venv/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 118, in create_json_schema
    return _mapping_schema(obj, seen)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/PycharmProjects/backend-user-form-api/.venv/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 212, in _mapping_schema
    **_properties({(k if isinstance(k, str) else safe_repr(k)): v for k, v in obj.items()}, seen),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/PycharmProjects/backend-user-form-api/.venv/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 337, in _properties
    if (value_schema := create_json_schema(value, seen)) not in PLAIN_SCHEMAS:
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/PycharmProjects/backend-user-form-api/.venv/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 120, in create_json_schema
    return _sqlalchemy_schema(obj, seen)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/PycharmProjects/backend-user-form-api/.venv/lib/python3.11/site-packages/logfire/_internal/json_schema.py", line 329, in _sqlalchemy_schema
    state = sa_inspect(obj)
            ^^^^^^^^^^^^^^^
  File "/root/PycharmProjects/backend-user-form-api/.venv/lib/python3.11/site-packages/sqlalchemy/inspection.py", line 147, in inspect
    raise exc.NoInspectionAvailable(
sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'form_api.schema.user_details.UserFormCreate'>

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire info
logfire="0.43.0"
platform="Linux-5.15.0-112-generic-x86_64-with-glibc2.35"
python="3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 11.4.0]"
[related_packages]
requests="2.32.3"
pydantic="2.7.4"
fastapi="0.110.0"
protobuf="4.25.3"
rich="13.7.1"
executing="2.0.1"
opentelemetry-api="1.25.0"
opentelemetry-exporter-otlp-proto-common="1.25.0"
opentelemetry-exporter-otlp-proto-http="1.25.0"
opentelemetry-instrumentation="0.46b0"
opentelemetry-instrumentation-asgi="0.46b0"
opentelemetry-instrumentation-asyncpg="0.46b0"
opentelemetry-instrumentation-fastapi="0.46b0"
opentelemetry-instrumentation-redis="0.46b0"
opentelemetry-instrumentation-sqlalchemy="0.46b0"
opentelemetry-instrumentation-system-metrics="0.46b0"
opentelemetry-proto="1.25.0"
opentelemetry-sdk="1.25.0"
opentelemetry-semantic-conventions="0.46b0"
opentelemetry-util-http="0.46b0"
```
