### ISSUE TITLE
Do not require auth if using custom exporters

### ISSUE THREAD

**Issue by astrojuanlu** [pydantic/logfire#298]
### Description

I tried Logfire for the first time and the UI looks so beautiful ✨ 

I then tried to set up a custom exporter using Jaeger as follows:

```
export OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318
export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4318/v1/traces
```

and the following `docker-compose.yaml`:

```yaml
services:
  jaeger:
    image: jaegertracing/all-in-one:1.58
    ports:
      - "4318:4318"
      - "16686:16686"
```

As expected, the logs were sent to my local Jaeger instance, and not to the Logfire UI. However, it still required me to do `logfire auth` and set up an empty project.

I then tried `export LOGFIRE_SEND_TO_LOGFIRE=0` and it did not ask me to auth, but also it didn't send the traces to Jaeger.

Am I missing something? And if indeed this is not yet possible, would you folks consider enabling that use case?
