### ISSUE TITLE
`logfire inspect` suggests irrelevant packages

### ISSUE THREAD

**Issue by keysmashes** [pydantic/logfire#330]
### Description

If I `logfire inspect`, it tells me I should set up integrations with httpx, requests, sqlite3, urllib, and urllib3. But of those, I only use httpx – it seems like it's recommending some of the others because logfire itself depends on them, and I have no idea about the rest.

- requests is a dependency of opentelemetry-exporter-otlp-proto-http
- sqlite3 doesn't appear to be used by any installed package
- urllib doesn't appear to be used by any installed package
- urllib3 is a dependency of requests

Looking at [`parse_inspect()`](https://github.com/pydantic/logfire/blob/0758b2418545d3c9d72303799aa51a9e74647078/logfire/_internal/cli.py#L200), I guess it's just seeing if the relevant package can be imported? But sqlite3 and urllib are stdlib packages, so that's not necessarily a useful check.

(sidenote: `logfire info`'s output is borderline-unreadable with my (light-background) terminal colourscheme)

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="0.47.0"
platform="macOS-14.5-arm64-arm-64bit"
python="3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 16.0.6 ]"
[related_packages]
requests="2.32.3"
pydantic="2.8.2"
protobuf="4.25.3"
rich="13.7.1"
executing="2.0.1"
opentelemetry-api="1.25.0"
opentelemetry-exporter-otlp-proto-common="1.25.0"
opentelemetry-exporter-otlp-proto-http="1.25.0"
opentelemetry-instrumentation="0.46b0"
opentelemetry-proto="1.25.0"
opentelemetry-sdk="1.25.0"
opentelemetry-semantic-conventions="0.46b0"
```
