### ISSUE TITLE
`pattern_m` instead of `pattern_match` on logfire.pydantic.dev

### ISSUE THREAD

**Issue by dpaleka** [pydantic/logfire#398]
### Description

This comes up upon expanding a scrubbing warning:
```
def scrubbing_callback(m: logfire.ScrubMatch):
    if (
        m.path == ('attributes', 'prompt')
        and m.pattern_m.group(0) == 'auth'
    ):
        return m.value
```

Replacing `pattern_m` with `pattern_match` worked.

![Screenshot 2024-08-25 at 08-53-22 Live · dpaleka_consistency-forecasting · Pydantic Logfire](https://github.com/user-attachments/assets/a62da9d8-0326-44ed-b6a1-84a8ccfe9783)

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="0.51.0"
platform="macOS-14.3.1-arm64-arm-64bit"
python="3.11.6 (main, May 23 2024, 12:47:05) [Clang 13.1.6 (clang-1316.0.21.2.5)]"
[related_packages]
requests="2.26.0"
pydantic="2.7.0"
openai="1.13.3"
protobuf="4.25.3"
rich="13.7.1"
executing="2.0.1"
opentelemetry-api="1.26.0"
opentelemetry-exporter-otlp-proto-common="1.26.0"
opentelemetry-exporter-otlp-proto-http="1.26.0"
opentelemetry-instrumentation="0.47b0"
opentelemetry-proto="1.26.0"
opentelemetry-sdk="1.26.0"
opentelemetry-semantic-conventions="0.47b0"
```
