### ISSUE TITLE
Pydantic instrumentation doesn't work seem to work natively on MacOS

### ISSUE THREAD

**Issue by dhruv-ahuja** [pydantic/logfire#411]
### Background
I am using Logfire for a FastAPI project that I'm developing, and Logfire isn't logging any stats for my Pydantic models. I realized this when I ran my app inside Docker and noticed a big increase in response time for an API returning about 100 pydantic nested models.
I am also supposed to see some logs for my Beanie (MongoDB) models that are initialized at app startup.

### Setup Info
Logfire version: 0.51.0; installed variants: fastapi, mongo, redis
Tried using env var as well as `PydanticPlugin` object with `'all'` value.
.env file has:
`LOGFIRE_PYDANTIC_PLUGIN_RECORD='all'` (tried the env var with and without string quotations, using Pydantic BaseSettings to read the env file)

Docker-compose environment values, with :
```docker
environment:
  - APP_ENVIRONMENT=prod
  - LOGFIRE_PYDANTIC_PLUGIN_RECORD=${LOGFIRE_PYDANTIC_PLUGIN_RECORD}
env_file:
  - .env
```

Log output when running webapp natively in MacOS:
```
(.venv) uvicorn src.main:app --reload --reload-dir src --reload-exclude .venv/ --port 8001
INFO:     Will watch for changes in these directories: ['/Users/dhruv/coding/python/projects/backend_burger/src']
INFO:     Uvicorn running on http://127.0.0.1:8001 (Press CTRL+C to quit)
INFO:     Started reloader process [83567] using WatchFiles
all
Logfire project URL: https://logfire.pydantic.dev/dhruv-ahuja/backend-burger
/Users/dhruv/coding/python/projects/backend_burger/.venv/lib/python3.11/site-packages/passlib/registry.py:43: PasslibWarning: handler names should be lower-case, and use underscores instead of hyphens: 'LambdaRuntimeClient' => 'lambdaruntimeclient'
  handler = get_crypt_handler(attr, None)
INFO:     Started server process [83569]
INFO:     Waiting for application startup.
07:48:35.629 connecting to database
07:48:36.465 successfully connected to database
07:48:36.476 scheduled 'upload_s3_logs' job to run weekly
07:48:36.480 scheduled 'delete_expired_blacklisted_tokens' job to run daily
07:48:36.481 scheduled 'price_prediction_run' job to run daily
INFO:     Application startup complete.
```

logs for startup event for dockerized app:
```
backend_burger  | [2024-09-01 07:54:01 +0000] [1] [INFO] Starting gunicorn 22.0.0
backend_burger  | [2024-09-01 07:54:01 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
backend_burger  | [2024-09-01 07:54:01 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
backend_burger  | [2024-09-01 07:54:01 +0000] [7] [INFO] Booting worker with pid: 7
backend_burger  | Logfire project URL: https://logfire.pydantic.dev/dhruv-ahuja/backend-burger
backend_burger  | /home/myuser/venv/lib/python3.11/site-packages/passlib/registry.py:43: PasslibWarning: handler names should be lower-case, and use underscores instead of hyphens: 'LambdaRuntimeClient' => 'lambdaruntimeclient'
backend_burger  |   handler = get_crypt_handler(attr, None)
backend_burger  | [2024-09-01 07:54:02 +0000] [7] [INFO] Started server process [7]
backend_burger  | [2024-09-01 07:54:02 +0000] [7] [INFO] Waiting for application startup.
backend_burger  | 07:54:02.579 connecting to database
backend_burger  | 07:54:03.357 Pydantic DocumentSettings validate_python
backend_burger  | 07:54:03.390 Pydantic DocumentSettings validate_python
backend_burger  | 07:54:03.533 Pydantic DocumentSettings validate_python
backend_burger  | 07:54:03.572 Pydantic LinkInfo validate_python
backend_burger  | 07:54:03.614 Pydantic DocumentSettings validate_python
backend_burger  | 07:54:03.690 Pydantic DocumentSettings validate_python
backend_burger  | 07:54:03.798 Pydantic DocumentSettings validate_python
backend_burger  | 07:54:03.872 successfully connected to database
backend_burger  | 07:54:03.880 scheduled 'upload_s3_logs' job to run weekly
backend_burger  | 07:54:03.885 scheduled 'delete_expired_blacklisted_tokens' job to run daily
backend_burger  | 07:54:03.887 scheduled 'price_prediction_run' job to run daily
backend_burger  | [2024-09-01 07:54:03 +0000] [7] [INFO] Application startup complete.
```

Please let me know if I am doing anything wrong, or if any other information is required.

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="0.51.0"
platform="macOS-14.6.1-arm64-arm-64bit"
python="3.11.6 (main, Nov  2 2023, 04:39:43) [Clang 14.0.3 (clang-1403.0.22.14.1)]"
[related_packages]
requests="2.32.3"
pydantic="2.7.4"
fastapi="0.111.0"
protobuf="4.25.4"
rich="13.7.1"
executing="2.0.1"
opentelemetry-api="1.26.0"
opentelemetry-exporter-otlp-proto-common="1.26.0"
opentelemetry-exporter-otlp-proto-http="1.26.0"
opentelemetry-instrumentation="0.47b0"
opentelemetry-instrumentation-asgi="0.47b0"
opentelemetry-instrumentation-fastapi="0.47b0"
opentelemetry-instrumentation-pymongo="0.47b0"
opentelemetry-instrumentation-redis="0.47b0"
opentelemetry-proto="1.26.0"
opentelemetry-sdk="1.26.0"
opentelemetry-semantic-conventions="0.47b0"
opentelemetry-util-http="0.47b0"
```
