### ISSUE TITLE
Query API Returns 400 Error

### ISSUE THREAD

**Issue by bllchmbrs** [pydantic/logfire#430]
### Description

_[related thread](https://pydanticlogfire.slack.com/archives/C06EDRBSAH3/p1726616902825689)_

## Async Client

```python

from logfire.experimental.query_client import AsyncLogfireQueryClient, LogfireQueryClient
query = """
  SELECT start_timestamp
  FROM records
  LIMIT 1
  """
async with AsyncLogfireQueryClient(read_token=read_token) as client:
            # Load data as JSON, in column-oriented format
    # json_cols = await client.query_json(sql=query)
    # print(json_cols)

    # Load data as JSON, in row-oriented format
    json_rows = await client.query_json_rows(sql=query)
    # print(json_rows)
    # arrow_table = await client.query_arrow(sql=query)
    # print(arrow_table)
```

```
---------------------------------------------------------------------------
QueryExecutionError                       Traceback (most recent call last)
Cell In[17], line 13
      2 query = """
      3   SELECT start_timestamp
      4   FROM records
      5   LIMIT 1
      6   """
      7 async with AsyncLogfireQueryClient(read_token=read_token) as client:
      8             # Load data as JSON, in column-oriented format
      9     # json_cols = await client.query_json(sql=query)
     10     # print(json_cols)
     11 
     12     # Load data as JSON, in row-oriented format
---> 13     json_rows = await client.query_json_rows(sql=query)
     14     # print(json_rows)
     15     # arrow_table = await client.query_arrow(sql=query)
     16     # print(arrow_table)

File [~/dev/project/.env/lib/python3.11/site-packages/logfire/experimental/query_client.py:273](http://localhost:8888/lab/tree/~/dev/project/.env/lib/python3.11/site-packages/logfire/experimental/query_client.py#line=272), in AsyncLogfireQueryClient.query_json_rows(self, sql, min_timestamp, max_timestamp, limit)
    265 async def query_json_rows(
    266     self,
    267     sql: str,
   (...)
    270     limit: int | None = None,
    271 ) -> RowQueryResults:
    272     """Query Logfire data and return the results as a row-oriented dictionary."""
--> 273     response = await self._query(
    274         accept='application[/json](http://localhost:8888/json)',
    275         sql=sql,
    276         min_timestamp=min_timestamp,
    277         max_timestamp=max_timestamp,
    278         limit=limit,
    279         row_oriented=True,
    280     )
    281     return response.json()

File [~/dev/project/.env/lib/python3.11/site-packages/logfire/experimental/query_client.py:343](http://localhost:8888/lab/tree/~/dev/project/.env/lib/python3.11/site-packages/logfire/experimental/query_client.py#line=342), in AsyncLogfireQueryClient._query(self, accept, sql, min_timestamp, max_timestamp, limit, row_oriented)
    341 params = self.build_query_params(sql, min_timestamp, max_timestamp, limit, row_oriented)
    342 response = await self.client.get('[/v1/query](http://localhost:8888/v1/query)', headers={'accept': accept}, params=params)
--> 343 self.handle_response_errors(response)
    344 return response

File [~/dev/project/.env/lib/python3.11/site-packages/logfire/experimental/query_client.py:93](http://localhost:8888/lab/tree/~/dev/project/.env/lib/python3.11/site-packages/logfire/experimental/query_client.py#line=92), in _BaseLogfireQueryClient.handle_response_errors(self, response)
     91 def handle_response_errors(self, response: Response) -> None:
     92     if response.status_code == 400:  # pragma: no cover
---> 93         raise QueryExecutionError(response.json())
     94     if response.status_code == 422:  # pragma: no cover
     95         raise QueryRequestError(response.json())

QueryExecutionError: {'detail': 'Execution error: error querying secondary index: error occurred while decoding column "schema_version": unexpected null; try decoding as an `Option`'}
```

## Sync Client

```python
from logfire.experimental.query_client import AsyncLogfireQueryClient, LogfireQueryClient
query = """
  SELECT start_timestamp
  FROM records
  LIMIT 1
  """
with LogfireQueryClient(read_token=read_token) as client:
            # Load data as JSON, in column-oriented format
    # json_cols = await client.query_json(sql=query)
    # print(json_cols)

    # Load data as JSON, in row-oriented format
    json_rows = client.query_json_rows(sql=query)
    # print(json_rows)
    # arrow_table = await client.query_arrow(sql=query)
    # print(arrow_table)
```
**Same error**

## Raw Requests

```python
import requests

# Define the base URL and your read token
base_url = 'https://logfire-api.pydantic.dev'


# Set the headers for authentication
headers = {
    'Authorization': f'Bearer {read_token}',
    'Content-Type': 'application/json'
}

# Define your SQL query
query = """
SELECT start_timestamp
FROM records
LIMIT 1
"""

# Prepare the query parameters for the GET request
params = {
    'sql': query
}

# Send the GET request to the Logfire API
response = requests.get(f'{base_url}/v1/query', params=params, headers=headers)

# Check the response status
if response.status_code == 200:
    print("Query Successful!")
    print(response.json())
else:
    print(f"Failed to execute query. Status code: {response.status_code}")
    print(response.text)
```

**Same error**

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="0.53.0"
platform="macOS-14.6.1-arm64-arm-64bit"
python="3.11.5 (main, Aug 11 2024, 20:30:18) [Clang 15.0.0 (clang-1500.3.9.4)]"
[related_packages]
requests="2.32.3"
pydantic="2.9.2"
fastapi="0.111.1"
openai="1.46.0"
protobuf="4.25.4"
rich="13.8.1"
executing="2.1.0"
opentelemetry-api="1.27.0"
opentelemetry-exporter-otlp-proto-common="1.27.0"
opentelemetry-exporter-otlp-proto-http="1.27.0"
opentelemetry-instrumentation="0.48b0"
opentelemetry-instrumentation-dbapi="0.48b0"
opentelemetry-instrumentation-httpx="0.48b0"
opentelemetry-instrumentation-psycopg2="0.48b0"
opentelemetry-proto="1.27.0"
opentelemetry-sdk="1.27.0"
opentelemetry-semantic-conventions="0.48b0"
opentelemetry-util-http="0.48b0"
```
