### ISSUE TITLE
Query API Error

### ISSUE THREAD

**Issue by bllchmbrs** [pydantic/logfire#436]
### Description

See #430.

Same queries, new error:

```
QueryExecutionError: {'detail': 'External error: External error: External error: External error: Arrow error: External error: Execution error: Invalid partitioning found on disk'}
```

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="0.53.0"
platform="macOS-14.6.1-arm64-arm-64bit"
python="3.11.5 (main, Aug 11 2024, 20:30:18) [Clang 15.0.0 (clang-1500.3.9.4)]"
[related_packages]
requests="2.32.3"
pydantic="2.9.2"
fastapi="0.111.1"
openai="1.46.0"
protobuf="4.25.4"
rich="13.8.1"
executing="2.1.0"
opentelemetry-api="1.27.0"
opentelemetry-exporter-otlp-proto-common="1.27.0"
opentelemetry-exporter-otlp-proto-http="1.27.0"
opentelemetry-instrumentation="0.48b0"
opentelemetry-instrumentation-dbapi="0.48b0"
opentelemetry-instrumentation-httpx="0.48b0"
opentelemetry-instrumentation-psycopg2="0.48b0"
opentelemetry-proto="1.27.0"
opentelemetry-sdk="1.27.0"
opentelemetry-semantic-conventions="0.48b0"
opentelemetry-util-http="0.48b0"
```
