### ISSUE TITLE
`LOGFIRE_SEND_TO_LOGFIRE` env var doesn't accept `if-token-present` as a value

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/logfire#441]
### Description

It would be very useful if it did, also more consistent with `configure()` kwargs

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="0.53.0"
platform="macOS-14.6.1-arm64-arm-64bit"
python="3.12.2 (main, Feb 25 2024, 03:55:42) [Clang 17.0.6 ]"
[related_packages]
requests="2.32.3"
pydantic="2.9.2"
fastapi="0.115.0"
openai="1.47.1"
protobuf="4.25.5"
rich="13.8.1"
executing="2.1.0"
opentelemetry-api="1.27.0"
opentelemetry-exporter-otlp-proto-common="1.27.0"
opentelemetry-exporter-otlp-proto-http="1.27.0"
opentelemetry-instrumentation="0.48b0"
opentelemetry-instrumentation-asgi="0.48b0"
opentelemetry-instrumentation-asyncpg="0.48b0"
opentelemetry-instrumentation-fastapi="0.48b0"
opentelemetry-instrumentation-httpx="0.48b0"
opentelemetry-instrumentation-system-metrics="0.48b0"
opentelemetry-proto="1.27.0"
opentelemetry-sdk="1.27.0"
opentelemetry-semantic-conventions="0.48b0"
opentelemetry-util-http="0.48b0"
```
