### ISSUE TITLE
autotracing broken with SyntaxError: no binding for nonlocal 'name' found

### ISSUE THREAD

**Issue by sasha-mm** [pydantic/logfire#495]
### Description

trying to auto-instrument with `logfire.install_auto_tracing(modules=['app'], min_duration=0.01)`

It is not clear what is wrong and why

function mentioned in the logs:
```
def generate_uuid():
    return str(uuid.uuid4()
```

```
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File .venv/lib/python3.12/site-packages/logfire/_internal/auto_trace/import_hook.py", line 104, in exec_module
    exec_source(self.source, filename, module.__name__, module.__dict__, self.logfire, self.min_duration)
  File .venv/lib/python3.12/site-packages/logfire/_internal/auto_trace/rewrite_ast.py", line 43, in exec_source
    exec(code, globs, globs)
  File app/a.py", line 4, in <module>
    from app.common.structs import ACR
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File .venv/lib/python3.12/site-packages/logfire/_internal/auto_trace/import_hook.py", line 104, in exec_module
    exec_source(self.source, filename, module.__name__, module.__dict__, self.logfire, self.min_duration)
  File .venv/lib/python3.12/site-packages/logfire/_internal/auto_trace/rewrite_ast.py", line 43, in exec_source
    exec(code, globs, globs)
  File app/common/structs.py", line 15, in <module>
    from app.common.util.utils import generate_uuid
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File .venv/lib/python3.12/site-packages/logfire/_internal/auto_trace/import_hook.py", line 104, in exec_module
    exec_source(self.source, filename, module.__name__, module.__dict__, self.logfire, self.min_duration)
  File .venv/lib/python3.12/site-packages/logfire/_internal/auto_trace/rewrite_ast.py", line 39, in exec_source
    tree = rewrite_ast(source, filename, logfire_name, module_name, logfire_instance, context_factories, min_duration)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File .venv/lib/python3.12/site-packages/logfire/_internal/auto_trace/rewrite_ast.py", line 60, in rewrite_ast
    return transformer.visit(tree)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File .rye/py/cpython@3.12.6/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File .rye/py/cpython@3.12.6/lib/python3.12/ast.py", line 483, in generic_visit
    value = self.visit(value)
            ^^^^^^^^^^^^^^^^^
  File .rye/py/cpython@3.12.6/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File .venv/lib/python3.12/site-packages/logfire/_internal/auto_trace/rewrite_ast.py", line 97, in visit_FunctionDef
    return super().visit_FunctionDef(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File .venv/lib/python3.12/site-packages/logfire/_internal/ast_utils.py", line 58, in visit_FunctionDef
    self.generic_visit(node)
  File .rye/py/cpython@3.12.6/lib/python3.12/ast.py", line 483, in generic_visit
    value = self.visit(value)
            ^^^^^^^^^^^^^^^^^
  File .rye/py/cpython@3.12.6/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File .venv/lib/python3.12/site-packages/logfire/_internal/auto_trace/rewrite_ast.py", line 97, in visit_FunctionDef
    return super().visit_FunctionDef(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File .venv/lib/python3.12/site-packages/logfire/_internal/ast_utils.py", line 58, in visit_FunctionDef
    self.generic_visit(node)
  File .rye/py/cpython@3.12.6/lib/python3.12/ast.py", line 483, in generic_visit
    value = self.visit(value)
            ^^^^^^^^^^^^^^^^^
  File .rye/py/cpython@3.12.6/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File .venv/lib/python3.12/site-packages/logfire/_internal/auto_trace/rewrite_ast.py", line 97, in visit_FunctionDef
    return super().visit_FunctionDef(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File .venv/lib/python3.12/site-packages/logfire/_internal/ast_utils.py", line 62, in visit_FunctionDef
    return self.rewrite_function(node, qualname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File .venv/lib/python3.12/site-packages/logfire/_internal/auto_trace/rewrite_ast.py", line 100, in rewrite_function
    if is_generator_function(node):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File .venv/lib/python3.12/site-packages/logfire/_internal/auto_trace/rewrite_ast.py", line 177, in is_generator_function
    code = compile(module_node, '<string>', 'exec')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 44
SyntaxError: no binding for nonlocal 'name' found
```

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="1.0.1"
platform="macOS-15.0.1-arm64-arm-64bit"
python="3.12.6 (main, Sep  9 2024, 21:36:32) [Clang 18.1.8 ]"
[related_packages]
requests="2.32.3"
pydantic="2.9.2"
fastapi="0.115.0"
openai="1.51.0"
protobuf="4.25.5"
rich="13.9.1"
executing="2.1.0"
opentelemetry-api="1.27.0"
opentelemetry-exporter-otlp-proto-common="1.27.0"
opentelemetry-exporter-otlp-proto-grpc="1.27.0"
opentelemetry-exporter-otlp-proto-http="1.27.0"
opentelemetry-instrumentation="0.48b0"
opentelemetry-instrumentation-alephalpha="0.31.4"
opentelemetry-instrumentation-anthropic="0.31.4"
opentelemetry-instrumentation-bedrock="0.31.4"
opentelemetry-instrumentation-chromadb="0.31.4"
opentelemetry-instrumentation-cohere="0.31.4"
opentelemetry-instrumentation-google-generativeai="0.31.4"
opentelemetry-instrumentation-groq="0.31.4"
opentelemetry-instrumentation-haystack="0.31.4"
opentelemetry-instrumentation-lancedb="0.31.4"
opentelemetry-instrumentation-langchain="0.31.4"
opentelemetry-instrumentation-llamaindex="0.31.4"
opentelemetry-instrumentation-marqo="0.31.4"
opentelemetry-instrumentation-milvus="0.31.4"
opentelemetry-instrumentation-mistralai="0.31.4"
opentelemetry-instrumentation-ollama="0.31.4"
opentelemetry-instrumentation-openai="0.31.4"
opentelemetry-instrumentation-pinecone="0.31.4"
opentelemetry-instrumentation-qdrant="0.31.4"
opentelemetry-instrumentation-replicate="0.31.4"
opentelemetry-instrumentation-requests="0.48b0"
opentelemetry-instrumentation-sqlalchemy="0.48b0"
opentelemetry-instrumentation-threading="0.48b0"
opentelemetry-instrumentation-together="0.31.4"
opentelemetry-instrumentation-transformers="0.31.4"
opentelemetry-instrumentation-urllib3="0.48b0"
opentelemetry-instrumentation-vertexai="0.31.4"
opentelemetry-instrumentation-watsonx="0.31.4"
opentelemetry-instrumentation-weaviate="0.31.4"
opentelemetry-proto="1.27.0"
opentelemetry-sdk="1.27.0"
opentelemetry-semantic-conventions="0.48b0"
opentelemetry-semantic-conventions-ai="0.4.1"
opentelemetry-util-http="0.48b0"
```
