### ISSUE TITLE
Invalid type NoneType for attribute 'fastapi.route.operation_id' value

### ISSUE THREAD

**Issue by ddahan** [pydantic/logfire#546]
### Description

Hi there.
When using FastAPI and Logfire, for each request, I have this strange log:

```
16:35:25.519   FastAPI arguments
Invalid type NoneType for attribute 'fastapi.route.operation_id' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
```

The endpoint works as expected.
How can I get rid of this?

Thanks.

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="1.3.0"
platform="Linux-6.10.4-linuxkit-aarch64-with-glibc2.36"
python="3.12.7 (main, Oct 19 2024, 18:29:53) [GCC 12.2.0]"
[related_packages]
requests="2.32.3"
pydantic="2.9.2"
fastapi="0.115.3"
protobuf="4.25.5"
rich="13.9.3"
executing="2.1.0"
opentelemetry-api="1.27.0"
opentelemetry-exporter-otlp-proto-common="1.27.0"
opentelemetry-exporter-otlp-proto-http="1.27.0"
opentelemetry-instrumentation="0.48b0"
opentelemetry-instrumentation-asgi="0.48b0"
opentelemetry-instrumentation-fastapi="0.48b0"
opentelemetry-instrumentation-sqlalchemy="0.48b0"
opentelemetry-proto="1.27.0"
opentelemetry-sdk="1.27.0"
opentelemetry-semantic-conventions="0.48b0"
opentelemetry-util-http="0.48b0"
```
