### ISSUE TITLE
Performance Issue: Just passing SecretStr instead of str, cause the execution time to go to >100ms from 5ms.

### ISSUE THREAD

**Issue by ManiMozaffar** [pydantic/logfire#56]
### Description

Check below code, Change secretstr, with "4". and try running the code again. That's kinda weird behavior.

```python
from datetime import datetime

import logfire
from pydantic import SecretStr

logfire.configure(service_name="New Service")


@logfire.instrument("Second Function", extract_args=True)
def foo(arg1: SecretStr, arg2: SecretStr):
    return f"{arg1}-{arg2}"


secretstr = SecretStr("4")
with logfire.span("One unit of work"):
    now = datetime.now()
    foo(secretstr, secretstr)
    logfire.info("xD")
    print((datetime.now() - now).total_seconds())

```

### Python, Logfire & OS Versions, related packages

```TOML
logfire="0.28.0"
platform="macOS-14.2.1-arm64-arm-64bit"
python="3.11.4 (v3.11.4:d2340ef257, Jun  6 2023, 19:15:51) [Clang 13.0.0 (clang-1300.0.29.30)]"
[related_packages]
requests="2.31.0"
pydantic="2.6.4"
fastapi="0.110.0"
protobuf="4.25.3"
rich="13.7.1"
opentelemetry-api="1.24.0"
opentelemetry-exporter-otlp-proto-common="1.24.0"
opentelemetry-exporter-otlp-proto-http="1.24.0"
opentelemetry-instrumentation="0.45b0"
opentelemetry-instrumentation-asgi="0.41b0"
opentelemetry-instrumentation-fastapi="0.41b0"
opentelemetry-instrumentation-redis="0.41b0"
opentelemetry-instrumentation-sqlalchemy="0.41b0"
opentelemetry-propagator-b3="1.23.0"
opentelemetry-proto="1.24.0"
opentelemetry-sdk="1.24.0"
opentelemetry-semantic-conventions="0.45b0"
opentelemetry-util-http="0.41b0"
```
