### ISSUE TITLE
auto-tracing "ValueError: empty body on With"

### ISSUE THREAD

**Issue by umbrella-yaroslav-graboveckiy** [pydantic/logfire#595]
### Description

In some cases, when we are facing with an "empty" function/method ast will write With block with an empty body and compile failing with non-informative exception. 
REF: https://github.com/pydantic/logfire/blob/main/logfire/_internal/ast_utils.py#L83-L91

```python
# test_module/test.py
def test_func():
    """
    Let's try to break auto-trace
    """
```

```python
# app.py
import logfire

logfire.install_auto_tracing(modules=['test_module'], min_duration=0)
logfire.configure(send_to_logfire=False)
import flask
import test_module

app = flask.Flask(__name__)
app.run()
```

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="2.1.1"
platform="macOS-14.4-arm64-arm-64bit"
python="3.11.10 (main, Sep  7 2024, 01:03:31) [Clang 15.0.0 (clang-1500.3.9.4)]"
[related_packages]
requests="2.31.0"
protobuf="4.25.5"
rich="13.9.4"
executing="2.1.0"
opentelemetry-api="1.24.0"
opentelemetry-distro="0.45b0"
opentelemetry-exporter-jaeger="1.21.0"
opentelemetry-exporter-jaeger-proto-grpc="1.21.0"
opentelemetry-exporter-jaeger-thrift="1.21.0"
opentelemetry-exporter-otlp="1.24.0"
opentelemetry-exporter-otlp-proto-common="1.24.0"
opentelemetry-exporter-otlp-proto-grpc="1.24.0"
opentelemetry-exporter-otlp-proto-http="1.24.0"
opentelemetry-instrumentation="0.45b0"
opentelemetry-instrumentation-celery="0.45b0"
opentelemetry-instrumentation-flask="0.45b0"
opentelemetry-instrumentation-redis="0.45b0"
opentelemetry-instrumentation-sqlalchemy="0.45b0"
opentelemetry-instrumentation-wsgi="0.45b0"
opentelemetry-proto="1.24.0"
opentelemetry-sdk="1.24.0"
opentelemetry-semantic-conventions="0.45b0"
opentelemetry-util-http="0.45b0"
```
