### ISSUE TITLE
Update Django setup doc to deal with local settings

### ISSUE THREAD

**Issue by ksamuel** [pydantic/logfire#620]
### Description

In the django doc (https://logfire.pydantic.dev/docs/integrations/django/) it is specified to `# Add the following lines at the end of the file`, which is very useful.

But on some django projects, they use a local settings pattern. E.G: you  may have a `settings.py` and a `local_settings.py` file instead of, say, env vars, for machine-specific settings. 

Because the `local_settings.py` file may be the one imported first by `wsgi.py`, if you put:

```python
logfire.configure()
logfire.instrument_django()
```

At the end of `settings.py` you will get no error, but also no telemetry. 

There are as many settings patterns are there are projects, some have "prod" settings file, some have cascading setting files with "common.py" files imported among others, some are dynamic with if/else imports, some modify `wsgi.py`... After all, it's just all Python.

So the doc needs to give a rule to know in which file you should put the `configure()` call otherwise plenty of people will feel like LogFire doesn't work and get zero feedback about why.

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="2.4.1"
platform="Linux-6.8.0-49-generic-x86_64-with-glibc2.39"
python="3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]"
[related_packages]
requests="2.32.3"
requests="2.32.3"
pydantic="2.10.0"
fastapi="0.115.5"
protobuf="5.28.3"
protobuf="5.28.3"
rich="13.7.1"
rich="13.9.4"
rich="13.9.4"
executing="2.1.0"
executing="2.1.0"
opentelemetry-api="1.28.2"
opentelemetry-api="1.28.2"
opentelemetry-exporter-otlp-proto-common="1.28.2"
opentelemetry-exporter-otlp-proto-common="1.28.2"
opentelemetry-exporter-otlp-proto-http="1.28.2"
opentelemetry-exporter-otlp-proto-http="1.28.2"
opentelemetry-instrumentation="0.49b2"
opentelemetry-instrumentation="0.49b2"
opentelemetry-instrumentation-asgi="0.49b2"
opentelemetry-instrumentation-django="0.49b2"
opentelemetry-instrumentation-fastapi="0.49b2"
opentelemetry-instrumentation-wsgi="0.49b2"
opentelemetry-proto="1.28.2"
opentelemetry-proto="1.28.2"
opentelemetry-sdk="1.28.2"
opentelemetry-sdk="1.28.2"
opentelemetry-semantic-conventions="0.49b2"
opentelemetry-semantic-conventions="0.49b2"
opentelemetry-util-http="0.49b2"
opentelemetry-util-http="0.49b2"
```
