### ISSUE TITLE
Add Sqlite instrumentation

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/logfire#635]
### Description

We need to add an `instrument_sqlite()` method, but first we need to get raw instrumentation working.

See https://github.com/pydantic/pydantic-ai/pull/107 where it doesn't seem to be working, perhaps because sqlite is running in another thread?

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="2.4.1"
platform="macOS-14.6.1-arm64-arm-64bit"
python="3.12.6 (main, Sep 20 2024, 17:42:55) [Clang 15.0.0 (clang-1500.0.40.1)]"
[related_packages]
requests="2.32.3"
pydantic="2.10.1"
fastapi="0.115.5"
openai="1.55.0"
protobuf="5.28.3"
rich="13.9.4"
executing="2.1.0"
opentelemetry-api="1.28.2"
opentelemetry-exporter-otlp-proto-common="1.28.2"
opentelemetry-exporter-otlp-proto-http="1.28.2"
opentelemetry-instrumentation="0.49b2"
opentelemetry-instrumentation-asgi="0.49b2"
opentelemetry-instrumentation-asyncpg="0.49b2"
opentelemetry-instrumentation-dbapi="0.49b2"
opentelemetry-instrumentation-fastapi="0.49b2"
opentelemetry-instrumentation-sqlite3="0.49b2"
opentelemetry-proto="1.28.2"
opentelemetry-sdk="1.28.2"
opentelemetry-semantic-conventions="0.49b2"
opentelemetry-util-http="0.49b2"
```
