### ISSUE TITLE
Logfire does not have exception info

### ISSUE THREAD

**Issue by vikigenius** [pydantic/logfire#636]
### Description

If I configure my StructLog processors like this

```
structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.processors.add_log_level,
        structlog.processors.TimeStamper(fmt="iso"),
        logfire.StructlogProcessor(),
        structlog.dev.ConsoleRenderer(
            colors=True, exception_formatter=RichTracebackFormatter(max_frames=1, show_locals=False, width=80)
        ),
    ],
)
```

I don't see the exception info in LogFire:

I just see this

```
{
  "connection_type": "http",
  "logfire.disable_console_log": true,
  "logfire.msg_template": "Uncaught exception",
  "path": "/register/github"
}
```

But if I add the  `structlog.processors.format_exc_info,`

```
structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.processors.add_log_level,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.format_exc_info,
        logfire.StructlogProcessor(),
        structlog.dev.ConsoleRenderer(
            colors=True, exception_formatter=RichTracebackFormatter(max_frames=1, show_locals=False, width=80)
        ),
    ],
)
```

I am able to get the exception

```
{
  "connection_type": "http",
  "exception": "...",
  "logfire.disable_console_log": true,
  "logfire.msg_template": "Uncaught exception",
  "path": "/register/github"
}
```
But this causes the RichTracebackFormatter to not work and I don't have pretty exceptions in the terminal.

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="2.4.1"
platform="Linux-6.6.63_1-x86_64-with-glibc2.39"
python="3.12.7 (main, Oct 16 2024, 04:37:19) [Clang 18.1.8 ]"
[related_packages]
requests="2.32.3"
pydantic="2.9.2"
protobuf="5.28.3"
rich="13.9.4"
executing="2.1.0"
opentelemetry-api="1.28.2"
opentelemetry-distro="0.49b2"
opentelemetry-exporter-otlp-proto-common="1.28.1"
opentelemetry-exporter-otlp-proto-http="1.28.1"
opentelemetry-instrumentation="0.49b2"
opentelemetry-instrumentation-asgi="0.49b2"
opentelemetry-instrumentation-sqlalchemy="0.49b2"
opentelemetry-proto="1.28.1"
opentelemetry-sdk="1.28.2"
opentelemetry-semantic-conventions="0.49b2"
opentelemetry-util-http="0.49b2"
```
