### ISSUE TITLE
Logfire with Celery ingores `token`

### ISSUE THREAD

**Issue by chrnmaxim** [pydantic/logfire#653]
### Description

Hello!

I'm running pytest with Celery (5.4.0) worker in Docker containers without a token and after each task I get the following output:

```
celery-worker-test-1  | 2024-12-07T11:16:39.350795862Z Traceback (most recent call last):
celery-worker-test-1  | 2024-12-07T11:16:39.350805992Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/context/__init__.py", line 154, in detach
celery-worker-test-1  | 2024-12-07T11:16:39.350810430Z     _RUNTIME_CONTEXT.detach(token)
celery-worker-test-1  | 2024-12-07T11:16:39.350814298Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/context/contextvars_context.py", line 50, in detach
celery-worker-test-1  | 2024-12-07T11:16:39.350817965Z     self._current_context.reset(token)  # type: ignore
celery-worker-test-1  | 2024-12-07T11:16:39.350821411Z TypeError: expected an instance of Token, got None
celery-worker-test-1  | 2024-12-07T11:16:39.521499430Z [2024-12-07 11:16:39,521: ERROR/ForkPoolWorker-7] Failed to export batch code: 401, reason: {"detail":"Invalid token"}
celery-worker-test-1  | 2024-12-07T11:16:47.664289545Z [2024-12-07 11:16:47,664: ERROR/ForkPoolWorker-7] Failed to export batch code: 401, reason: {"detail":"Invalid token"}
celery-worker-test-1  | 2024-12-07T11:16:47.724731606Z [2024-12-07 11:16:47,724: ERROR/ForkPoolWorker-8] Failed to export batch code: 401, reason: {"detail":"Invalid token"
```

Moreover, even if there is a token (and I'm actually receiving logs from virtual machine), the same warning appears in Celery logs after each tasks proceed.

```
[2024-12-07 11:30:00,026: ERROR/ForkPoolWorker-1] Failed to detach context
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/opentelemetry/context/__init__.py", line 154, in detach                     _RUNTIME_CONTEXT.detach(token)
  File "/usr/local/lib/python3.10/site-packages/opentelemetry/context/contextvars_context.py", line 50, in detach           self._current_context.reset(token)  # type: ignore
  TypeError: expected an instance of Token, got None  
  ```

### Python, Logfire & OS Versions, related packages (not required)

Logfire info from local PC

```TOML
logfire="1.2.0"
platform="Windows-10-10.0.26100-SP0"
python="3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]"
[related_packages]
requests="2.32.3"
pydantic="2.7.1"
fastapi="0.115.0"
protobuf="4.25.5"
rich="13.9.2"
executing="2.1.0"
opentelemetry-api="1.27.0"
opentelemetry-exporter-otlp-proto-common="1.27.0"
opentelemetry-exporter-otlp-proto-http="1.27.0"
opentelemetry-instrumentation="0.48b0"
opentelemetry-instrumentation-asgi="0.48b0"
opentelemetry-instrumentation-celery="0.48b0"
opentelemetry-instrumentation-fastapi="0.48b0"
opentelemetry-instrumentation-sqlalchemy="0.48b0"
opentelemetry-proto="1.27.0"
opentelemetry-sdk="1.27.0"
opentelemetry-semantic-conventions="0.48b0"
opentelemetry-util-http="0.48b0"
```

Logfire info from VM

```TOML
logfire="1.2.0"
platform="Linux-6.8.0-40-generic-x86_64-with-glibc2.36"
python="3.10.16 (main, Dec  4 2024, 20:37:22) [GCC 12.2.0]"
[related_packages]
requests="2.32.3"
pydantic="2.7.1"
fastapi="0.115.0"
protobuf="4.25.5"
rich="13.9.2"
tomli="2.0.2"
executing="2.1.0"
opentelemetry-api="1.27.0"
opentelemetry-exporter-otlp-proto-common="1.27.0"
opentelemetry-exporter-otlp-proto-http="1.27.0"
opentelemetry-instrumentation="0.48b0"
opentelemetry-instrumentation-asgi="0.48b0"
opentelemetry-instrumentation-celery="0.48b0"
opentelemetry-instrumentation-fastapi="0.48b0"
opentelemetry-instrumentation-sqlalchemy="0.48b0"
opentelemetry-proto="1.27.0"
opentelemetry-sdk="1.27.0"
opentelemetry-semantic-conventions="0.48b0"
opentelemetry-util-http="0.48b0"
```
