### ISSUE TITLE
Anthropic Beta Tool Use Blocks do not render in llm convo in span

### ISSUE THREAD

**Issue by andrew-stelmach** [pydantic/logfire#666]
### Description

As seen in [this](https://logfire.pydantic.dev/andrew-stelmach/suno-computer-use?q=trace_id%3D%270e2bad513bb206a9337760bc560a1047%27+and+span_id%3D%27a463fa8912deb903%27&spanId=a463fa8912deb903&traceId=0e2bad513bb206a9337760bc560a1047&since=2024-12-11T23%3A12%3A05.863923Z&until=2024-12-11T23%3A12%3A10.993881Z) span, we don't get any llm convo rendering. As opposed to [this](https://logfire.pydantic.dev/andrew-stelmach/suno-computer-use?q=trace_id%3D%27126683c34329e2f4442929ce91745aa3%27+and+span_id%3D%279234acd38c83b8ab%27&spanId=9234acd38c83b8ab&traceId=126683c34329e2f4442929ce91745aa3&since=2024-12-11T22%3A43%3A04.875035Z&until=2024-12-11T22%3A43%3A13.327701Z) span, we do get the convo rendering. Essentially just adding `logfire.instrument_anthropic()` to [this](https://github.com/deedy/mac_computer_use) repo.

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="2.7.0"
platform="macOS-15.2-arm64-arm-64bit"
python="3.12.4 (v3.12.4:8e8a4baf65, Jun  6 2024, 17:33:18) [Clang 13.0.0 (clang-1300.0.29.30)]"
[related_packages]
requests="2.32.3"
pydantic="2.10.3"
protobuf="5.29.1"
rich="13.9.4"
executing="2.1.0"
opentelemetry-api="1.29.0"
opentelemetry-exporter-otlp-proto-common="1.29.0"
opentelemetry-exporter-otlp-proto-http="1.29.0"
opentelemetry-instrumentation="0.50b0"
opentelemetry-proto="1.29.0"
opentelemetry-sdk="1.29.0"
opentelemetry-semantic-conventions="0.50b0"
```
