### ISSUE TITLE
Anthropic streaming response does not get logged

### ISSUE THREAD

**Issue by qria** [pydantic/logfire#672]
### Description

Logfire does not log anthropic streaming response.

This is the resulting dashboard when I stream both openai and anthropic:

![image](https://github.com/user-attachments/assets/caf82289-84e6-4df7-a294-98ab8e4b2f22)

Anthropic streaming request gets logged but response does not.

Simple reproduction here: https://github.com/qria/logfire-bug-reproduction

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="2.7.1"
platform="macOS-14.6.1-arm64-arm-64bit"
python="3.11.9 (main, Jul 11 2024, 18:34:45) [Clang 15.0.0 (clang-1500.3.9.4)]"
[related_packages]
requests="2.32.3"
pydantic="2.10.3"
openai="1.57.4"
protobuf="5.29.1"
rich="13.9.4"
executing="2.1.0"
opentelemetry-api="1.29.0"
opentelemetry-exporter-otlp-proto-common="1.29.0"
opentelemetry-exporter-otlp-proto-http="1.29.0"
opentelemetry-instrumentation="0.50b0"
opentelemetry-proto="1.29.0"
opentelemetry-sdk="1.29.0"
opentelemetry-semantic-conventions="0.50b0"
```
