### ISSUE TITLE
On live view, if the log message is too long it hides the components below

### ISSUE THREAD

**Issue by arn314** [pydantic/logfire#678]
### Description

This is a frontend issue. On live view, if the log message is too long it hides the components below.

I think it's due to not having proper height and overflow CSS attributes on either the span element (containing the log) or one of its parent elements. FWIW, setting these attributes on span element fixes it: `block h-24 overflow-scroll`

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="2.7.1"
platform="macOS-10.16-x86_64-i386-64bit"
python="3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 16.0.6 ]"
[related_packages]
requests="2.32.3"
pydantic="2.9.2"
protobuf="5.29.1"
rich="13.9.4"
executing="2.1.0"
opentelemetry-api="1.29.0"
opentelemetry-exporter-otlp-proto-common="1.29.0"
opentelemetry-exporter-otlp-proto-http="1.29.0"
opentelemetry-instrumentation="0.50b0"
opentelemetry-proto="1.29.0"
opentelemetry-sdk="1.29.0"
opentelemetry-semantic-conventions="0.50b0"
```
