### ISSUE TITLE
spans sometimes never close

### ISSUE THREAD

**Issue by tvt173** [pydantic/logfire#741]
### Description

Sometimes my spans never close. They just linger as `<ongoing?>`. This happens somewhat frequently (maybe a couple of times out of a few hundred). I see this happen both when running locally (via WSL) and on my server (linux) that I would use for production. What could be causing this?
![image](https://github.com/user-attachments/assets/bd59c472-48bb-404b-9b6e-dfb377d40fca)

Not sure if this could be part of the issue, but I do use multiprocessing in my package, and there are messages being sent from different processes concurrently.

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="2.11.0"
platform="Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35"
python="3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0]"
[related_packages]
requests="2.32.3"
pydantic="2.8.2"
protobuf="5.29.2"
rich="13.7.1"
tomli="2.0.1"
executing="2.0.1"
opentelemetry-api="1.29.0"
opentelemetry-exporter-otlp-proto-common="1.29.0"
opentelemetry-exporter-otlp-proto-http="1.29.0"
opentelemetry-instrumentation="0.50b0"
opentelemetry-instrumentation-dbapi="0.50b0"
opentelemetry-instrumentation-jinja2="0.50b0"
opentelemetry-instrumentation-requests="0.50b0"
opentelemetry-instrumentation-sqlite3="0.50b0"
opentelemetry-instrumentation-tornado="0.50b0"
opentelemetry-instrumentation-urllib="0.50b0"
opentelemetry-instrumentation-urllib3="0.50b0"
opentelemetry-proto="1.29.0"
opentelemetry-sdk="1.29.0"
opentelemetry-semantic-conventions="0.50b0"
opentelemetry-util-http="0.50b0"
```
