### ISSUE TITLE
Invalid type NoneType for attribute 'http.port' value.

### ISSUE THREAD

**Issue by mplemay** [pydantic/logfire#749]
### Description

After upgrading to `2.11.1` from `2.11.0`,  I get a deluge of warnings (see below). For context, if I do not configure `logfire` I do not get any warnings. My logfire configuration is as follows:
```python
logfire.configure(
    send_to_logfire="if-token-present",
    token=(None if SETTINGS.LOGFIRE_API_KEY is None else SETTINGS.LOGFIRE_API_KEY.get_secret_value()),
    console=(None if SETTINGS.DEBUG else False),
)
```

```
Invalid type NoneType for attribute 'http.port' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
Invalid type NoneType for attribute 'http.port' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
...
```

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="2.11.1"
platform="macOS-15.2-arm64-arm-64bit"
python="3.12.8 (main, Dec  3 2024, 18:42:41) [Clang 16.0.0 (clang-1600.0.26.4)]"
[related_packages]
requests="2.32.3"
pydantic="2.10.4"
fastapi="0.115.6"
openai="1.58.1"
protobuf="5.29.2"
rich="13.9.4"
executing="2.1.0"
opentelemetry-api="1.29.0"
opentelemetry-exporter-otlp-proto-common="1.29.0"
opentelemetry-exporter-otlp-proto-http="1.29.0"
opentelemetry-instrumentation="0.50b0"
opentelemetry-instrumentation-aiohttp-client="0.50b0"
opentelemetry-instrumentation-asgi="0.50b0"
opentelemetry-instrumentation-fastapi="0.50b0"
opentelemetry-instrumentation-sqlalchemy="0.50b0"
opentelemetry-proto="1.29.0"
opentelemetry-sdk="1.29.0"
opentelemetry-semantic-conventions="0.50b0"
opentelemetry-util-http="0.50b0"
```
