### ISSUE TITLE
TypeError: MeterProvider.get_meter() got multiple values for argument 'version' during FastAPI instrumentation

### ISSUE THREAD

**Issue by alon710** [pydantic/logfire#838]
### Description

Hi Logfire team,

I'm encountering an issue when instrumenting my FastAPI application with Logfire.
When I call logfire.instrument_fastapi, I get the following error:

```bash
TypeError: MeterProvider.get_meter() got multiple values for argument 'version'
The error appears to be triggered from within Logfire's metrics integration when it calls provider.get_meter(). I suspect that the version argument is inadvertently being passed more than once (perhaps both positionally and as a keyword).
```
Minimal Reproduction Code:

```python
import logfire
from fastapi import FastAPI

app = FastAPI()

# This call triggers the error:
logfire.instrument_fastapi(app=app, excluded_urls=("/metrics", "/health", "/docs", "/openapi.json", "/static/*"))
```
Questions:

Is this a known issue with the Logfire integration for FastAPI?
Could this be due to a compatibility problem with a specific version of OpenTelemetry?
Are there any workarounds or fixes in progress to resolve this error?

Thanks in advance for your help.

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="3.5.1"
platform="macOS-15.2-arm64-arm-64bit"
python="3.12.8 (main, Dec  3 2024, 18:42:41) [Clang 16.0.0 (clang-1600.0.26.4)]"
[related_packages]
requests="2.32.3"
pydantic="2.10.5"
fastapi="0.115.7"
protobuf="5.29.3"
rich="13.9.4"
executing="2.1.0"
opentelemetry-api="1.29.0"
opentelemetry-exporter-otlp-proto-common="1.29.0"
opentelemetry-exporter-otlp-proto-http="1.29.0"
opentelemetry-instrumentation="0.50b0"
opentelemetry-instrumentation-asgi="0.50b0"
opentelemetry-instrumentation-fastapi="0.50b0"
opentelemetry-instrumentation-httpx="0.50b0"
opentelemetry-proto="1.29.0"
opentelemetry-sdk="1.29.0"
opentelemetry-semantic-conventions="0.50b0"
opentelemetry-util-http="0.50b0"
```
