### ISSUE TITLE
weird behaviour with uvicorn

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/logfire#850]
### Description

If I run uvicorn normally (e.g. `uv run uvicorn app:app`), I see two logs, one from logfire and one from uvicorn

```
16:11:29.487 GET /
INFO:     172.17.0.1:59302 - "GET / HTTP/1.1" 404 Not Found
```
If I run uvicorn with `--log-level warning`, then I see neither. This seems wrong.

### Python, Logfire & OS Versions, related packages (not required)

```TOML
Logfire project URL: 
https://logfire.pydantic.dev/samuelcolvin/pydantic-run-proxy
^C16:14:14.146 GET /
16:14:18.774 GET /
code/proxy.pydantic.run 0 ➤ uv run logfire info
logfire="3.5.3"
platform="macOS-14.6.1-arm64-arm-64bit-Mach-O"
python="3.13.0 (main, Oct 16 2024, 08:05:40) [Clang 18.1.8 ]"
[related_packages]
requests="2.32.3"
pydantic="2.10.6"
protobuf="5.29.3"
rich="13.9.4"
executing="2.2.0"
opentelemetry-api="1.30.0"
opentelemetry-exporter-otlp-proto-common="1.30.0"
opentelemetry-exporter-otlp-proto-http="1.30.0"
opentelemetry-instrumentation="0.51b0"
opentelemetry-instrumentation-asgi="0.51b0"
opentelemetry-instrumentation-httpx="0.51b0"
opentelemetry-instrumentation-starlette="0.51b0"
opentelemetry-instrumentation-system-metrics="0.51b0"
opentelemetry-proto="1.30.0"
opentelemetry-sdk="1.30.0"
opentelemetry-semantic-conventions="0.51b0"
opentelemetry-util-http="0.51b0"
```
