### ISSUE TITLE
Error shown in my logs

### ISSUE THREAD

**Issue by philipohagan** [pydantic/logfire#862]
### Description

```
Log:Failed to introspect calling code. Please report this issue to Logfire. Falling back to normal message formatting which may result in loss of information if using an f-string. Set inspect_arguments=False in logfire.configure() to suppress this warning. The problem was:
`executing` failed to find a node.
```

https://logfire.pydantic.dev/philipohagan/music-library?q=trace_id%3D%270194ff62677de08facb5cae272587eb9%27+and+span_id%3D%273b63ef81990c1473%27&spanId=3b63ef81990c1473&traceId=0194ff62677de08facb5cae272587eb9&since=2025-02-13T12%3A57%3A06.685186Z&until=2025-02-13T13%3A07%3A08.105720Z

### Python, Logfire & OS Versions, related packages (not required)

```TOML
(venv) pohagan@Phils-MacBook-Pro Music Library % logfire info
logfire="3.5.3"
platform="macOS-15.3-arm64-arm-64bit"
python="3.12.9 (main, Feb  4 2025, 14:38:38) [Clang 16.0.0 (clang-1600.0.26.6)]"
[related_packages]
requests="2.32.3"
pydantic="2.10.6"
fastapi="0.115.8"
openai="1.62.0"
protobuf="5.29.3"
rich="13.9.4"
executing="2.2.0"
opentelemetry-api="1.30.0"
opentelemetry-exporter-otlp-proto-common="1.30.0"
opentelemetry-exporter-otlp-proto-grpc="1.30.0"
opentelemetry-exporter-otlp-proto-http="1.30.0"
opentelemetry-instrumentation="0.51b0"
opentelemetry-instrumentation-asgi="0.51b0"
opentelemetry-instrumentation-fastapi="0.51b0"
opentelemetry-proto="1.30.0"
opentelemetry-sdk="1.30.0"
opentelemetry-semantic-conventions="0.51b0"
opentelemetry-util-http="0.51b0"
```
