### ISSUE TITLE
Authenticating for the first time whilst already logged in

### ISSUE THREAD

**Issue by philsheard** [pydantic/logfire#869]
### Description

I setup a new account on Logfire web and then installed the package using uv.

When I ran `logfire auth` the browser window opened but I got an error page.

The CLI registered this as a successful auth, so it's just the web behaviour that you'll need to look into.

https://logfire.pydantic.dev/auth/authenticate >>

<img width="528" alt="Image" src="https://github.com/user-attachments/assets/a9afd43e-9f34-410e-be39-e82b14b5c9e5" />

I can supply more details if needed

### Python, Logfire & OS Versions, related packages (not required)

```TOML
="3.5.3"
platform="macOS-15.1-arm64-arm-64bit"
python="3.11.11 (main, Feb  5 2025, 18:58:27) [Clang 19.1.6 ]"
[related_packages]
requests="2.32.3"
pydantic="2.10.6"
protobuf="5.29.3"
rich="13.9.4"
executing="2.2.0"
opentelemetry-api="1.30.0"
opentelemetry-exporter-otlp-proto-common="1.30.0"
opentelemetry-exporter-otlp-proto-http="1.30.0"
opentelemetry-instrumentation="0.51b0"
opentelemetry-proto="1.30.0"
opentelemetry-sdk="1.30.0"
opentelemetry-semantic-conventions="0.51b0"
```
