### ISSUE TITLE
Type checking on `logfire.span` is broken

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/logfire#884]
### Description

Using `with logfire.span(...):` I'm seeing

```
  /Users/samuel/code/spiced-ham/app/analyse.py:171:10 - error: Object of type "LogfireSpan" cannot be used with "with" because it does not correctly implement __exit__ (reportGeneralTypeIssues)
```

We should have tests to make sure this doesn't happen!

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="3.6.1"
platform="macOS-15.3.1-arm64-arm-64bit-Mach-O"
python="3.13.0 (main, Oct 16 2024, 08:05:40) [Clang 18.1.8 ]"
[related_packages]
requests="2.32.3"
pydantic="2.10.6"
openai="1.63.2"
protobuf="5.29.3"
rich="13.9.4"
executing="2.2.0"
opentelemetry-api="1.30.0"
opentelemetry-exporter-otlp-proto-common="1.30.0"
opentelemetry-exporter-otlp-proto-http="1.30.0"
opentelemetry-instrumentation="0.51b0"
opentelemetry-instrumentation-asgi="0.51b0"
opentelemetry-instrumentation-httpx="0.51b0"
opentelemetry-instrumentation-starlette="0.51b0"
opentelemetry-proto="1.30.0"
opentelemetry-sdk="1.30.0"
opentelemetry-semantic-conventions="0.51b0"
opentelemetry-util-http="0.51b0"
```
