### ISSUE TITLE
Crash on bad json.

### ISSUE THREAD

**Issue by vincentdavis** [pydantic/logfire#902]
### Description

I am migrating data between two postgres db's one has native JSON field the other is using Djangos JSON fields. 
I am getting errors related to converting /U0000.
I tried to log the json with logfire and logfire crashed. 
-     "logfire[asgi,django,psycopg]>=3.5.3",
-     "pydantic>=2.10.6",
```
[2025-03-03 14:17:34 +0000] [76] [INFO] Booting worker with pid: 76

    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.13/site-packages/logfire/_internal/main.py", line 355, in info

    self.log('info', msg_template, attributes, tags=_tags, exc_info=_exc_info)

    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/.venv/lib/python3.13/site-packages/logfire/_internal/main.py", line 679, in log

    msg, extra_attrs, msg_template = logfire_format_with_magic(

                                     ~~~~~~~~~~~~~~~~~~~~~~~~~^

        msg_template,

        ^^^^^^^^^^^^^

    ...<2 lines>...

        fstring_frame=fstring_frame,

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    )

    ^

  File "/app/.venv/lib/python3.13/site-packages/logfire/_internal/formatter.py", line 330, in logfire_format_with_magic

    chunks, extra_attrs, new_template = chunks_formatter.chunks(

                                        ~~~~~~~~~~~~~~~~~~~~~~~^

        format_string,

        ^^^^^^^^^^^^^^

    ...<2 lines>...

        fstring_frame=fstring_frame,

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    )

Logfire project URL: https://logfire.pydantic.dev/vincentdavis/app-gotta-bike
```

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="3.6.2"
platform="macOS-15.3.1-arm64-arm-64bit"
python="3.12.4 (v3.12.4:8e8a4baf65, Jun  6 2024, 17:33:18) [Clang 13.0.0 (clang-1300.0.29.30)]"
[related_packages]
requests="2.32.3"
pydantic="2.10.6"
protobuf="5.29.3"
rich="13.9.4"
executing="2.2.0"
opentelemetry-api="1.30.0"
opentelemetry-exporter-otlp-proto-common="1.30.0"
opentelemetry-exporter-otlp-proto-http="1.30.0"
opentelemetry-instrumentation="0.51b0"
opentelemetry-instrumentation-asgi="0.51b0"
opentelemetry-instrumentation-dbapi="0.51b0"
opentelemetry-instrumentation-django="0.51b0"
opentelemetry-instrumentation-psycopg="0.51b0"
opentelemetry-instrumentation-wsgi="0.51b0"
opentelemetry-proto="1.30.0"
opentelemetry-sdk="1.30.0"
opentelemetry-semantic-conventions="0.51b0"
opentelemetry-util-http="0.51b0"
```
