### ISSUE TITLE
OpenAI instrumentation crashes when there is a request error from server

### ISSUE THREAD

**Issue by yiphei** [pydantic/logfire#908]
### Description

When there is a request error from the server, the OpenAI instrumentation does not handle it and instead crashes, thus crashing my entire app. For instance, it crashes on a ChatCompletion object like the following
```
ChatCompletion(id=None, choices=None, created=None, model=None, object=None, service_tier=None, system_fingerprint=None, usage=None, error={'message': 'Overloaded', 'code': 502, 'metadata': {'provider_name': 'Anthropic', 'slug': 'anthropic/claude-3-7-sonnet-20250219', 'upstream_stream': True, 'stream': False, 'generation_id': 'gen-1741148018-uI6JXaoJUT8P3rZ9bfzL', 'isDownstreamPipeClean': True, 'isErrorUpstreamFault': True}}, user_id='user_2tDvfUkvnoIfWZAr7gBcidgH8cj')
```

and it crashes in this location: https://github.com/pydantic/logfire/blob/06b5531896dbae3bfc43e21e733fcdc208312c7a/logfire/_internal/integrations/llm_providers/openai.py#L125 

As you can see from the code, it makes the faulty assumption that `response.choices` is always not null.

However, I do want to note that these errors are Anthropic server errors. This is because I use OpenRouter, which allows me to use Anthropic models with OpenAI API. So perhaps the instrumentation only gracefully handles OpenAI server errors and nothing else?

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="3.7.0"
platform="macOS-15.3.1-arm64-arm-64bit"
python="3.11.9 (main, Feb 20 2025, 22:54:01) [Clang 16.0.0 (clang-1600.0.26.6)]"
[related_packages]
requests="2.32.3"
pydantic="2.9.2"
fastapi="0.115.5"
openai="1.65.3"
protobuf="5.29.2"
rich="13.9.4"
executing="2.1.0"
opentelemetry-api="1.29.0"
opentelemetry-exporter-otlp-proto-common="1.29.0"
opentelemetry-exporter-otlp-proto-http="1.29.0"
opentelemetry-instrumentation="0.50b0"
opentelemetry-proto="1.29.0"
opentelemetry-sdk="1.29.0"
opentelemetry-semantic-conventions="0.50b0"
```
