### ISSUE TITLE
openai-agents doesn't seem to clear GLOBAL_TRACE_PROVIDER list

### ISSUE THREAD

**Issue by codefromthecrypt** [pydantic/logfire#922]
### Description

If I run this code with the correct ENV variables, it sends to logfire, but also has an error like this:

```
Tracing client error 401: {
  "error": {
    "message": "Incorrect API key provided: unused. You can find your API key at https://platform.openai.com/account/api-keys.",
    "type": "invalid_request_error",
    "param": null,
    "code": "invalid_api_key"
  }
}
```

code
```python
import os

import httpx
import logfire
from agents import Agent, ModelSettings, OpenAIProvider, RunConfig, Runner, function_tool
from agents.tracing import GLOBAL_TRACE_PROVIDER

GLOBAL_TRACE_PROVIDER.shutdown()
GLOBAL_TRACE_PROVIDER.set_processors([])

logfire.configure()
logfire.instrument_openai_agents()


@function_tool
def get_latest_elasticsearch_version() -> str:
    """Returns the latest GA version of Elasticsearch in "X.Y.Z" format."""

    response = httpx.get("https://artifacts.elastic.co/releases/stack.json")
    response.raise_for_status()
    releases = response.json()["releases"]

    # Fetch releases and filter out non-release versions (e.g., -rc1) and
    # remove any " GA" suffix.
    versions = []
    for r in releases:
        v = r["version"].removesuffix(" GA")
        if "-" in r["version"]:
            continue
        versions.append(v)

    if not versions:
        raise ValueError("No valid versions found")

    # "8.9.1" > "8.10.0", so coerce to a numeric tuple: (8,9,1) < (8,10,0)
    return max(versions, key=lambda v: tuple(map(int, v.split("."))))


def main():
    model_name = os.getenv("CHAT_MODEL", "gpt-4o-mini")
    model = OpenAIProvider(use_responses=False).get_model(model_name)
    agent = Agent(
        name="version_assistant",
        tools=[get_latest_elasticsearch_version],
        model=model,
        model_settings=ModelSettings(temperature=0),
    )

    result = Runner.run_sync(
        starting_agent=agent,
        input="What is the latest version of Elasticsearch?",
        run_config=RunConfig(workflow_name="GetLatestElasticsearchVersion"),
    )
    print(result.final_output)


if __name__ == "__main__":
    main()
```

If I paste this above `logfire.configure()`, it is ok
```
GLOBAL_TRACE_PROVIDER.shutdown()
GLOBAL_TRACE_PROVIDER.set_processors([])
```

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="3.8.0"
platform="macOS-15.3.1-arm64-arm-64bit"
python="3.12.8 | packaged by conda-forge | (main, Dec  5 2024, 14:19:53) [Clang 18.1.8 ]"
[related_packages]
requests="2.32.3"
pydantic="2.10.6"
openai="1.66.2"
protobuf="5.29.3"
rich="13.9.4"
executing="2.2.0"
opentelemetry-api="1.30.0"
opentelemetry-exporter-otlp="1.30.0"
opentelemetry-exporter-otlp-proto-common="1.30.0"
opentelemetry-exporter-otlp-proto-grpc="1.30.0"
opentelemetry-exporter-otlp-proto-http="1.30.0"
opentelemetry-instrumentation="0.51b0"
opentelemetry-instrumentation-system-metrics="0.51b0"
opentelemetry-proto="1.30.0"
opentelemetry-resource-detector-azure="0.1.5"
opentelemetry-resourcedetector-gcp="1.8.0a0"
opentelemetry-sdk="1.30.0"
opentelemetry-sdk-extension-aws="2.1.0"
opentelemetry-semantic-conventions="0.51b0"
```
