### ISSUE TITLE
SyntaxError when using 'await' expressions inside f-strings

### ISSUE THREAD

**Issue by Sbargaoui** [pydantic/logfire#942]
### Description

When using await expressions inside f-strings passed to logfire logging methods, a SyntaxError: 'await' outside function exception is raised, causing the application to crash. This occurs despite the code being executed within an async function context.

Here's an example : 

```
import asyncio
import logfire

async def get_content():
    await asyncio.sleep(0.1)
    return "response content"

async def main():
    logfire.configure()
    # This line triggers the error
    logfire.error(f"res error: {await get_content()}")

if __name__ == "__main__":
    asyncio.run(main())
```

It produces : 
```
Traceback (most recent call last):
  ...
  File ".../formatter.py", line 387, in compile_formatted_value
    value_code = compile(source, '<fvalue1>', 'eval')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<fvalue1>", line 1
SyntaxError: 'await' outside function
```
The issue appears to be in logfire's handling of f-strings. It attempts to extract and re-evaluate the expressions in f-strings, but when it encounters an await expression, it attempts to evaluate it outside of an async context, leading to the SyntaxError.

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="3.9.0"
platform="macOS-14.3-arm64-arm-64bit-Mach-O"
python="3.13.2 (main, Feb  4 2025, 14:51:09) [Clang 16.0.0 (clang-1600.0.26.6)]"
[related_packages]
requests="2.32.3"
protobuf="5.29.4"
rich="13.9.4"
executing="2.2.0"
opentelemetry-api="1.31.1"
opentelemetry-exporter-otlp-proto-common="1.31.1"
opentelemetry-exporter-otlp-proto-http="1.31.1"
opentelemetry-instrumentation="0.52b1"
opentelemetry-proto="1.31.1"
opentelemetry-sdk="1.31.1"
opentelemetry-semantic-conventions="0.52b1"
```
