### ISSUE TITLE
port missing from HTTP requests where you'd expect it

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/logfire#948]
### Description

Noticed while creating #947:

![Image](https://github.com/user-attachments/assets/0a96f07e-4691-4df1-92f1-03264fba2d44)

These requests are all to http://localhost:3001

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="3.9.0"
platform="macOS-15.3.2-arm64-arm-64bit"
python="3.12.7 (main, Oct 16 2024, 07:12:08) [Clang 18.1.8 ]"
[related_packages]
requests="2.32.3"
pydantic="2.10.6"
fastapi="0.115.8"
openai="1.68.2"
protobuf="5.29.4"
rich="13.9.4"
executing="2.2.0"
opentelemetry-api="1.30.0"
opentelemetry-exporter-otlp-proto-common="1.31.1"
opentelemetry-exporter-otlp-proto-http="1.31.1"
opentelemetry-instrumentation="0.52b1"
opentelemetry-instrumentation-asgi="0.51b0"
opentelemetry-instrumentation-asyncpg="0.51b0"
opentelemetry-instrumentation-dbapi="0.51b0"
opentelemetry-instrumentation-fastapi="0.51b0"
opentelemetry-instrumentation-httpx="0.52b1"
opentelemetry-instrumentation-sqlite3="0.51b0"
opentelemetry-proto="1.31.1"
opentelemetry-sdk="1.31.1"
opentelemetry-semantic-conventions="0.52b1"
opentelemetry-util-http="0.52b1"
```
