### ISSUE TITLE
Logfire incompatible with the new Anthropic Thinking mode.

### ISSUE THREAD

**Issue by qria** [pydantic/logfire#951]
### Description

Anthropic recently introduced [extended thinking mode] in claude 3.7 and it is not compatible with current logfire.

Specifically, [ThinkingBlock] and [RedactedThinkingBlock] has been added as a valid response [content block]. This raises an error in anthropic integration, because [current implementation] assumes the response block is either a text block or a tool call block. Here's a traceback of one such error:

```
AttributeError: 'ThinkingBlock' object has no attribute 'name'
  File "anthropic/resources/messages/messages.py", line 2165, in create
    return await self._post(
  File "anthropic/_base_client.py", line 1914, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "anthropic/_base_client.py", line 1608, in request
    return await self._request(
  File "logfire/_internal/integrations/llm_providers/llm_provider.py", line 138, in instrumented_llm_request_async
    response = on_response_fn(await original_request_method(*args, **kwargs), span)
  File "logfire/_internal/integrations/llm_providers/anthropic.py", line 73, in on_response
    message['tool_calls'] = [
  File "logfire/_internal/integrations/llm_providers/anthropic.py", line 77, in <listcomp>
    'name': block.name,  # type: ignore
  File "pydantic/main.py", line 891, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
```

Also due to the introduction of new block type, the response can have multiple heterogenous blocks as response even without the tool calls. For example, following is a valid response from a single call:

```json
{
  "content": [
    {
      "type": "thinking",
      "thinking": "Let me analyze this step by step...",
      "signature": "WaUjzkypQ2mUEVM36O2TxuC06KN8xyfbJwyem2dw3URve/op91XWHOEBLLqIOMfFG/UvLEczmEsUjavL...."
    },
    {
      "type": "redacted_thinking",
      "data": "EmwKAhgBEgy3va3pzix/LafPsn4aDFIT2Xlxh0L5L8rLVyIwxtE3rAFBa8cr3qpP..."
    },
    {
      "type": "text",
      "text": "Based on my analysis..."
    }
  ]
}
```

Note that you can trigger a redaction in thinking blocks with a [magic string].

[extended thinking mode]: https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking

[ThinkingBlock]: https://github.com/anthropics/anthropic-sdk-python/blob/main/src/anthropic/types/thinking_block.py#L10

[RedactedThinkingBlock]: https://github.com/anthropics/anthropic-sdk-python/blob/main/src/anthropic/types/redacted_thinking_block.py#L10

[content block]: https://github.com/anthropics/anthropic-sdk-python/blob/main/src/anthropic/types/content_block.py#L15

[current implementation]: https://github.com/pydantic/logfire/blob/v3.9.0/logfire/_internal/integrations/llm_providers/anthropic.py#L68-L81

[magic string]: https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking#example-streaming-with-redacted-thinking:~:text=as%20your%20prompt%3A-,ANTHROPIC_MAGIC_STRING_TRIGGER_REDACTED_THINKING_46C9A13E193C177646C7398A98432ECCCE4C1253D5E2D82641AC0E52CC2876CB,-When%20passing%20thinking

### Python, Logfire & OS Versions, related packages (not required)

```TOML
                             
logfire="3.9.0"
platform="macOS-15.3.2-arm64-arm-64bit"
python="3.11.9 (main, Jul 11 2024, 18:34:45) [Clang 15.0.0 (clang-1500.3.9.4)]"
[related_packages]
requests="2.32.3"
pydantic="2.10.5"
fastapi="0.103.2"
openai="1.65.2"
protobuf="4.25.5"
rich="13.9.4"
executing="2.1.0"
opentelemetry-api="1.27.0"
opentelemetry-exporter-otlp-proto-common="1.27.0"
opentelemetry-exporter-otlp-proto-http="1.27.0"
opentelemetry-instrumentation="0.48b0"
opentelemetry-instrumentation-asgi="0.48b0"
opentelemetry-instrumentation-dbapi="0.48b0"
opentelemetry-instrumentation-fastapi="0.48b0"
opentelemetry-instrumentation-psycopg="0.48b0"
opentelemetry-proto="1.27.0"
opentelemetry-sdk="1.27.0"
opentelemetry-semantic-conventions="0.48b0"
opentelemetry-util-http="0.48b0"
```
