### ISSUE TITLE
OpenaiCompletionStreamState is outdated

### ISSUE THREAD

**Issue by da-niao-dan** [pydantic/logfire#975]
### Description

the code at https://github.com/pydantic/logfire/blob/main/logfire/_internal/integrations/llm_providers/openai.py
line 92
content_from_completions chunk.choices[0].text
is probably outdated

running this line will give us " 'Choice' object has no attribute 'text' " error

According to the latest open api config, https://platform.openai.com/docs/api-reference/chat-streaming/streaming, the stream response is of different format. 

I have changed this line to `chunk.choices[0].delta.content`
and the code works fine.

Is this a bug? And do you want a PR for this?

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="3.12.0"
platform="Linux-6.8.0-54-generic-x86_64-with-glibc2.39"
python="3.9.21 | packaged by conda-forge | (main, Dec  5 2024, 13:51:40) 
[GCC 13.3.0]"
[related_packages]
requests="2.32.3"
pydantic="2.9.2"
openai="1.39.0"
protobuf="5.29.4"
rich="13.6.0"
tomli="2.2.1"
executing="2.2.0"
opentelemetry-api="1.29.0"
opentelemetry-exporter-otlp-proto-common="1.29.0"
opentelemetry-exporter-otlp-proto-http="1.29.0"
opentelemetry-instrumentation="0.50b0"
opentelemetry-proto="1.29.0"
opentelemetry-sdk="1.29.0"
opentelemetry-semantic-conventions="0.50b0"
```
