### ISSUE TITLE
module 'logfire' has no attribute 'instrument_pydantic_ai'

### ISSUE THREAD

**Issue by nguyenth-sieuviet** [pydantic/logfire#984]
### Description

```
logfire.configure(
    token='my_token',
    environment='local',
    send_to_logfire=True,
    console=False
)

logfire.instrument_pydantic_ai()

Agent(LLMModels.gemini_2_Flash_Lite).run_sync('hello').data
```

"""
AttributeError: module 'logfire' has no attribute 'instrument_pydantic_ai'
"""

### Python, Logfire & OS Versions, related packages (not required)

```TOML
logfire="3.5.3"
platform="Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35"
python="3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]"
[related_packages]
requests="2.32.3"
pydantic="2.10.3"
fastapi="0.115.11"
openai="1.69.0"
protobuf="5.29.3"
rich="13.9.4"
tomli="2.2.1"
executing="2.2.0"
opentelemetry-api="1.30.0"
opentelemetry-exporter-otlp-proto-common="1.30.0"
opentelemetry-exporter-otlp-proto-http="1.30.0"
opentelemetry-instrumentation="0.51b0"
opentelemetry-proto="1.30.0"
opentelemetry-sdk="1.30.0"
opentelemetry-semantic-conventions="0.51b0"
```
